### ISSUE TITLE
[FEATURE REQUEST] Multiple returns

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#10]
Wow, sorry for multiple feature requesting! :sweat_smile:

So, I'm trying to add the `returns` command multiple times in same function, for example:

```pascal
{
  Allocates a new memory space and zero-initialize it.
  @param ASize[in] Memory size to be allocated.
  @return Pointer of the allocated zero-initialized memory.
  @return @code(NULL) When size is @code(0) or no memory space.
}
function BrookAlloc(ASize: NativeUInt): Pointer;
```

but it is not supported. However, what do you think about to support the `retval` command? It would generate something like this:

![image](https://user-images.githubusercontent.com/1456829/36355276-8bb0a9fc-14bf-11e8-824e-44bd36dd8053.png)

It is another Doxygen feature that IMHO would be nice to implement in PasDoc since Pascal programming also allows multiple return values in same function:

![image](https://user-images.githubusercontent.com/1456829/36355290-ad4d6082-14bf-11e8-8a29-f091306a8ea7.png)

Thank you!

**Comment by michaliskambi** [comment]
You can already write something like

```
@returns(Pointer of the allocated zero-initialized memory.

  Returns values:
  
  @definitionList(
    @itemLabel(nil)
    @item(When something.)
    @itemLabel(Non-nil)
    @item(When something else.)
  )
)
```

And you can use `@unorderedList` instead of `@definitionList`, you can add `@itemSpacing(Compact)`.

Granted, it looks much more verbose, but it's possible. It would look more concise once we support Markdown:)

**Comment by silvioprog** [comment]
Perfect! I'm going to test it tonight and reply the other FRs. :smiley:

**Comment by silvioprog** [comment]
@michaliskambi , thanks for sharing `@definitionList`, but I can't align the generated list to the bottom. 🙁

My declaration is:

```pascal
{
  Allocates a new memory space and zero-initialize it.
  @param(ASize[in] Memory size to be allocated.)
  @return Pointer of the allocated zero-initialized memory.

  @bold(Returns values:)

  @definitionList(
    @itemLabel(@code(nil))
    @item(When size is @code(0) or no memory space.)
  )
}
function BrookAlloc(ASize: NativeUInt): Pointer;
```

and the result is:

![image](https://user-images.githubusercontent.com/1456829/36464684-f1dc6dbe-16af-11e8-8eb2-792995c6e3fe.png)

but I would like to get something like this (picture edited by [GIMP](https://www.gimp.org)):

![image](https://user-images.githubusercontent.com/1456829/36464778-67f1a50a-16b0-11e8-9121-0787a092c378.png)

So, is there any option to keep the same sorting as declared in the code?

**Comment by michaliskambi** [comment]
Right now, you cannot place some part of the "normal description" (the text outside of `@return`) lower than the `@return` output. 

But there is a solution, I presented it inside my earlier comment :) Just place the whole `@definitionList` inside the `@return` parameter. Remember to use parenthesis to have the `@return` parameter multi-line:

```
@return(Pointer of the allocated zero-initialized memory.

  Returns values:
  
  @definitionList(
    @itemLabel(nil)
    @item(When something.)
    @itemLabel(Non-nil)
    @item(When something else.)
  )
)
```

The output is like this (and this picture was *not* edited in GIMP :) :) ) :

![screenshot-2018-2-21 a](https://user-images.githubusercontent.com/1076978/36505696-98cf1b5e-1754-11e8-9211-0ad0cd4d4c57.png)

**Comment by silvioprog** [comment]
Wow, perfect!

Fixed as you commented:

```pascal
{
  Allocates a new memory space and zero-initialize it.

  @param(ASize[in] Memory size to be allocated.)

  @return(Pointer of the allocated zero-initialized memory.

    @bold(Returns values:)

    @definitionList(
      @itemLabel(@code(nil))
      @item(When size is @code(0) or no memory space.)
    )
  )
}
```

the generated doc was:

![image](https://user-images.githubusercontent.com/1456829/36626174-6782bdf8-190c-11e8-83ad-01041a8d1619.png)

Thank you very much dude! :+1: :smiley: :+1:
