### ISSUE TITLE
Make new release available

### ISSUE THREAD

**Issue by SlMaker** [pasdoc/pasdoc#105]
Please make a new release - other one is over 2 years old and it got some really nice features since then! :smile:

**Comment by michaliskambi** [comment]
Agreed.

Let me wait a bit for https://github.com/pasdoc/pasdoc/pull/100 to be finished, as it upgrades Tipue and jQuery, and I'd like to have them upgraded before the next release. If that doesn't happen soon, I'll upgrade them without this PR.

And then, release! :)

**Comment by jdelauney** [comment]
Hi, I've amend the PR it will good now i think

**Comment by SlMaker** [comment]
Any news @michaliskambi ?

**Comment by michaliskambi** [comment]
I have it in my TODO:) Will happen in November.

**Comment by SlMaker** [comment]
Maybe a christmas present? :)

**Comment by michaliskambi** [comment]
I'll try earlier :) Sorry for failing -- had it in my TODO, along with a bunch of other TODOs, and I kept postponing it due to lack of time. I'll definitely try to make a release in December.

Note that in the meantime, we always have https://github.com/pasdoc/pasdoc/wiki/DevelopmentSnapshots which are automatically updated after every commit+push.

**Comment by michaliskambi** [comment]
I actually started working on it around Christmas 2020 :)

But I was displeased by our lack of "proper" website. We have excellent documentation in the wiki ( https://github.com/pasdoc/pasdoc/wiki ), but I felt that the presentation of it on GitHub wiki doesn't do it justice, e.g. we cannot have nice prominent "download" links, and the ultra-useful "sidebar" gets lost.

So I decided to make a website, using our wiki contents :) This is now mostly finished. It uses Jekyll to convert wiki content (in AsciiDoctor) to HTML, applies some nice style, and is available under a proper simple URL:

https://pasdoc.github.io/

Now that I'm happy with it, new release will follow soon :)

**Comment by SlMaker** [comment]
:sunglasses: :+1:

**Comment by michaliskambi** [comment]
New PasDoc release is ready on https://github.com/pasdoc/pasdoc/releases/tag/v0.16.0 !

The list of changes is on that page, as well as in new (Markdownified) changelog on https://github.com/pasdoc/pasdoc/blob/master/ChangeLog.md .

Our website links to this download prominently from https://pasdoc.github.io/ now.

Please help in announcing this release everywhere among Pascal developers!
