### ISSUE TITLE
Compile pasdoc_gui in Delphi 10.2

### ISSUE THREAD

**Issue by cadetill** [pasdoc/pasdoc#110]
When I compile pasdoc_gui en Delphi 10.2 I have this error

[dcc32 Error] E1026 File not found: 'pasdoc_gui.res'

How to solve it? 

Thanks

**Comment by michaliskambi** [comment]
1. Note that the primary PasDoc GUI (in `source/gui`) is developed with open-source Lazarus.

    So if you refer to this application, the answer is that you cannot compile it with Delphi.

2. We also have a Delphi version of the GUI, in `source/delphi_gui`, but it's not maintained actively, it is behind the Lazarus version. It will be most probably removed at some point. 

    So if you refer to this application, I am interested if there is a fix... but, realistically, this application is obsolete.

**Comment by cadetill** [comment]
perfect then! I will download Lazaros to compile it :-)

thanks!

**Comment by michaliskambi** [comment]
As I understand we can close this issue.
