### ISSUE TITLE
Nitpicking editorial correction suggested

### ISSUE THREAD

**Issue by Processor-reference** [pasdoc/pasdoc#111]
I have three issues - this is item 1 - and because they are on separate points I'll write them separately. First, let me say I think Pasdoc is a fantastic program, and as such I'd like to see it made better. Thus, I am going to descend to a little nit-picking. 

> In pasdoc_tokenizer, at line 215, there is the following enumerated type:
  **TSymbolType = (SYM_PLUS, SYM_MINUS, SYM_ASTERISK, SYM_SLASH, SYM_EQUAL,
     SYM_LESS_THAN, SYM_LESS_THAN_EQUAL, SYM_GREATER_THAN,
     SYM_GREATER_THAN_EQUAL, SYM_LEFT_BRACKET, SYM_RIGHT_BRACKET,
     SYM_COMMA, SYM_LEFT_PARENTHESIS, SYM_RIGHT_PARENTHESIS, SYM_COLON,
     SYM_SEMICOLON, SYM_ROOF, SYM_PERIOD, SYM_AT,
     SYM_DOLLAR, SYM_ASSIGN, SYM_RANGE, SYM_POWER,
    { SYM_BACKSLASH may occur when writing char constant "^\",
      see ../../tests/ok_caret_character.pas }
    SYM_BACKSLASH);**
That corresponds to the following constant from line 231:
 SymbolNames: array[TSymbolType] of string =
  ( '+', '-', '*', '/', '=', '<', '<=', '>', '>=', '[', ']', ',',
    '(', ')', ':', ';', '^', '.', '@', '$', ':=', '..', '\*\*', '\\' );

If you want to be using the same terms as are used in Pascal such as compilers, two of the symbols should be renamed. 

1. "SYM_ROOF", the name for the caret ^, is normally pronounced "dereference" and in compilers it's either called that or 'deref".  Thus, it probably should be changed to SYM_DEREFERENCE and references to SYM_ROOF changed
2. "SYM_ASSIGN", the name for colon equals := is normally pronounced "becomes" (the Pascal 8000 compiler developed by the (now defunct) Australian Atomic Energy commission from as far back as 1980 uses the term "becomessy" to refer to the symbol.

So, to make thing clearer I recommend these changes

Paul Robinson <XDPascal@XDPascal.com>  "The lessons of history teach us - if they teach us anything - that no one learns the lessons history teaches us."

**Comment by michaliskambi** [comment]
As for `SYM_ROOF` -- yeah, that's a weird name, I agree. Changed to `SYM_DEREFERENCE` per your suggestion. Note that in FPC it is called `_CARET`.

As for `SYM_ASSIGN`, here I consider the current name good. It is commonly called "assignment operator" and used in phrases like "you make an assignment", "assignment instruction", "you assign something to some variable" (in Pascal and other languages). I would say that calling is "becomes" would be non-standard. Looking at FPC, they call it `_ASSIGNMENT`.

Thank you for nitpicking, keep it coming :)
