### ISSUE TITLE
error and correction in pasdoc_scanner with suggested improvement

### ISSUE THREAD

**Issue by Processor-reference** [pasdoc/pasdoc#112]
In Pasdoc_scanner.pas, at line 1239, is the following:

     begin
      try
        if T.IsKeyWord(KEY_AND) then
          Result := Result and ParseExpression
        else
        if T.IsKeyWord(KEY_OR) then
          Result := Result and ParseExpression
        else
        if T.IsSymbol(SYM_EQUAL) then
          Result := Result = ParseExpression
        else
            raise EInvalidIfCondition.Create(
       'Cannot handle opertator function "%s" in $if / $elseif',     [T.Description]);

Clearly, the fragment

     if T.IsKeyWord(KEY_OR) then
          Result := Result and ParseExpression
        else

should read

      if T.IsKeyWord(KEY_OR) then
          Result := Result or ParseExpression
        else

Additionally, conditional expressions don't just use equal; the main program of the Free Pascal compiler, pp.pas itself uses a comparison to be sure the compiler itself is being compiled with a version of itself that supports all the features the compiler uses. Thus, the other comparison operators should be included in conditional checks, so when the above fix is made, I suggest changing the code as follows, at this point:

     if T.IsSymbol(SYM_EQUAL) then
          Result := Result = ParseExpression
        else
            raise

Insert new code between the "else" and "raise". Replace this with:

    if T.IsSymbol(SYM_EQUAL) then
          Result := Result = ParseExpression
        else
    if T.IsSymbol(SYM_LESS_THAN) then
          Result := Result < ParseExpression
        else
    if T.IsSymbol(SYM_LESS_THAN_EQUAL) then
          Result := Result <= ParseExpression
        else
    if T.IsSymbol(SYM_GREATER_THAN) then
          Result := Result > ParseExpression
        else
    if T.IsSymbol( SYM_GREATER_THAN_EQUAL) then
          Result := Result >= ParseExpression
        else
            raise

This will then cover all the test conditions one could put in conditional compilation.

Thank you for your attention.

Paul 

Paul Robinson <XDPascal@XDPascal.com> "The lessons of history teach us - if they teach us anything - that no one learns the lessons that history teaches us."

**Comment by michaliskambi** [comment]
Thank you for catching this! I applied all your changes.

As for comparison operators, note that our current logic in PasDoc_Scanner.pas only works on Boolean expressions anyway. So e.g. we will not handle comparisons with integers, like the one in FPC you mention:

```
{$if FPC_FULLVERSION<20600}
  {$fatal At least FPC 2.6.0 is required to compile the compiler}
{$endif}
```

Still, comparison operators work on Booleans too, and now we're more ready for handling non-Boolean expressions too :) Thanks!
