### ISSUE TITLE
Wrong item name in navigation for introduction

### ISSUE THREAD

**Issue by opensimply** [pasdoc/pasdoc#116]
On making the "HtmlOutput", the project name specified by the "--title" option is used in the navigation panel instead of the value specified by the "@shorttitle" in the introduction file.

The command:  pasdoc --title Projectname --format html --introduction startpage.txt
The startpage.txt content: @shorttitle(start page) @title(Project title) some text

Using the  "HtmlHelp" output no such an issue is occurred.

**Comment by michaliskambi** [comment]
Ah, indeed. A recent change made the "project title" in the navigation panel be a link to the introduction. In effect, the project title was used as a link to the introduction, and the `@shortTitle` in the introduction was ignored.

Fixed, `@shortTitle` will be used if specified.

Along with a related fix in that logic (it was sometimes possible to have an invisible link to the introduction, now we use string "Introduction" as a fallback if nothing else specified).

**Comment by opensimply** [comment]
Thank you!
