### ISSUE TITLE
[FEATURE REQUEST] Advanced Record Support

### ISSUE THREAD

**Issue by jdelauney** [pasdoc/pasdoc#12]
Hi, 

I wanted to test the generation of documentation on my project. Only the result is chaotic.

The problem is that my library is essentially composed of advanced recordings with private, public fields and internal functions.

Apart from (temporarily) passing them to 'class'.

Is there a tip with pasdoc?

Do you take charge of this in the future?

Best regards

**Comment by michaliskambi** [comment]
Please submit an exact source code that doesn't work -- PasDoc generally supports advanced records, as least the simple cases I tested. If some particular egde-case is not parsed OK, we can fix it.

**Comment by jdelauney** [comment]
Hi, after uncheck "implicit" option in pasdoc gui and by refine my comments. I've finally go a result. But some little errors with html out. i'll open new issue

**Comment by michaliskambi** [comment]
Glad that it solved :)

BTW Note that the "implicit" option does not affect records -- the default visibility section of a records is always `public`. The "implicit" option and visibilty ( https://github.com/pasdoc/pasdoc/wiki/ImplicitVisibilityOption , https://github.com/pasdoc/pasdoc/wiki/IncludeByVisibility ) are only relevant for `class`.
