### ISSUE TITLE
noAutoLink and noAutoLinkHere tag not listed under supported tags in wiki

### ISSUE THREAD

**Issue by Bi0T1N** [pasdoc/pasdoc#120]
Hi,
just noticed that the `noAutoLink` and `noAutoLinkHere` tags are not listed under supported tags, only under the command line category `-auto-link, --auto-link-exclude`. As I'm not sure if this is intended or not - here is the report 😄

**Comment by michaliskambi** [comment]
They should be listed :) Fixed, thank you!
