### ISSUE TITLE
Path no found error on using the @includeCode tag in additional file

### ISSUE THREAD

**Issue by opensimply** [pasdoc/pasdoc#122]
The @includeCode tag does not recognize the path to the file with the external code when using this tag in the additional file.

[includeCodeIssue.zip](https://github.com/pasdoc/pasdoc/files/6083034/includeCodeIssue.zip)

**Comment by michaliskambi** [comment]
Thanks for reporting! Fixed and added your testcases to our automatic tests, so the bug will not return :)

**Comment by opensimply** [comment]
The "txt" directory of additional file (`--additional=txt\somefile.txt`)  is not taken into account. The path is retrieved one level up. 
So, the tag  in the "somefile.txt" file should be specified as `@includeCode(external\externalcode.pas)` instead of `@includeCode(..\external\externalcode.pas)` as it is specified in the  "main.pas" file.

Is it OK?

**Comment by michaliskambi** [comment]
The current PasDoc behavior is correct. I mean, if you have a hierarchy like in your testcase:

```
external/
  externalcode.pas
pas/
  main.pas
txt/
  somefile.txt
```

...then both `main.pas` and `somefile.txt` should reference the `externalcode.pas` as `@includeCode(../external/externalcode.pas)`. The path inside `@includeCode` is relative to the file that contains the tag, so to the `somefile.txt`. This way it doesn't matter whether that file was referenced on the command-line as

```
pasdoc --additional=txt/somefile.txt pas/main.pas
```

or

```
cd txt/
pasdoc --additional=somefile.txt ../pas/main.pas
```

So, this is deliberate. Also somewhat documented, https://pasdoc.github.io/IncludeCodeTag -- """The filename [...] is relative to the Pascal source file defining this identifier""". Docs are not precise in this case, you have introduction/conclusion, not a Pascal source in this case -- but it works the same. In a way, the introduction/conclusion act as "special, weird Pascal item" for PasDoc.

Note: use `/` to make it work on both Windows and Unix. The backslash `\` will only work on Windows, as on Unix is not a special character.

**Comment by opensimply** [comment]
Thank you for such a detailed explanation and advice!
