### ISSUE TITLE
Change font size of return and parameter title text

### ISSUE THREAD

**Issue by hsauro** [pasdoc/pasdoc#125]
I noticed that the font size for the return and parameter labels are very small due to the use of h6 for example:

<h6 class="description_section">Returns</h6>

Is there any way to increase its size without recompiling pasdoc?
I'm using the provided css file 

/* Ascanio Pressato pasdoc_v0.7.css compliant with CVS PasDoc 2005-06-26 */

**Comment by hsauro** [comment]
I just realized I can redefine h6 in the css file.

**Comment by michaliskambi** [comment]
I think the CSS from Ascanio Pressato was old (possibly not updated to the latest PasDoc).

If you have an issue with the default CSS, please post a screenshot and/or PR, we can improve it :)
