### ISSUE TITLE
Warning: Found non-link tag when expanding descriptions of "DoSomething" in unit (Example Docs)

### ISSUE THREAD

**Issue by PolywickStudio** [pasdoc/pasdoc#126]
DIPasDoc 0.8.10 [2006-07-06|DELPHI 4|MSWindows|32]
Documentation Generator for Pascal Unit Source Code Files.
Latest Version: http://www.yunqa.de/delphi/

Warning: No Output Language specified, using primary ("English")
Info:    Starting Source File Parsing ...
Info:    Parsing "..\..\(example.pas)"
Info:    ... 1 Source File(s) parsed
Info:    Creating links ...
Info:    ... 6 links created
Info:    Expanding descriptions ...
Warning: Found non-link tag when expanding descriptions of "DoSomething" in unit unitAESSetting
Warning: Found non-link tag when expanding descriptions of "DoSomething" in unit unitAESSetting
Warning: Found non-link tag when expanding descriptions of "DoSomething" in unit unitAESSetting
Warning: Found non-link tag when expanding descriptions of "DoSomething" in unit unitAESSetting
Info:    ... Descriptions expanded
Info:    Writing docs for unit "example.pas"
Info:    Done, worked 00:00 minutes(s)

Example code:

{ Do something with name and value.
  @param(Name is a string with the item's name)
  @param(Value is a string with the item's value)
  @returns(@true on success, @false otherwise)
  @raises(EUnknownItem if the name can not be found)
}
function DoSomething(const Name: string; const Value: string): boolean;

What should I do to get rid of the warning?

This is from your example page.
https://pasdoc.github.io/ParamReturnsRaisesTag

**Comment by michaliskambi** [comment]
> DIPasDoc 0.8.10 [2006-07-06|DELPHI 4|MSWindows|32]
> Documentation Generator for Pascal Unit Source Code Files.
> Latest Version: http://www.yunqa.de/delphi/

You are using a fork of PasDoc from 2006, released 15 years ago :) 

Download the latest version from https://pasdoc.github.io/ and the tags documented on https://pasdoc.github.io/ParamReturnsRaisesTag will work OK.

The latest source code doesn't contain the `Found non-link tag when expanding descriptions` warning anywhere.
