### ISSUE TITLE
Charset Brazilian

### ISSUE THREAD

**Issue by vcintra** [pasdoc/pasdoc#128]
I'm generation the documentation using Brazilian UTF8 charset, the titles are correct, but my descriptions are not. 
Exemple: 
![image](https://user-images.githubusercontent.com/28271306/140756960-b04caae8-ff43-40b9-9e45-7e9e6a4bb694.png)

What could I be doing wrong?

**Comment by michaliskambi** [comment]
Can you submit a testcase? I.e. a simple project to reproduce the problem, and how do call PasDoc (using PasDoc GUI or command-line, and post the exact command you use).

My first suspicion would be that your source code does not have Brazilian special characters correctly encoded in UTF-8.

Also please specify whether you use an official PasDoc binary from https://pasdoc.github.io/ , on what system. If you compile PasDoc yourself, mention which compiler do you use.

**Comment by vcintra** [comment]
Thank you for your help. My problem was using GitLab Pages. I adopted another strategy of exporting the generated files and I got success.
