### ISSUE TITLE
Inline variable declarations

### ISSUE THREAD

**Issue by LeoUpperThrower4** [pasdoc/pasdoc#129]
PasDoc raises exception when trying to parse inline variable declaration.

![image](https://user-images.githubusercontent.com/29781030/146232572-4197ed81-b7c3-4c10-992a-128771171e1a.png)

**Stack:**
![image](https://user-images.githubusercontent.com/29781030/146233005-8e2d4700-ba29-4b1e-959e-6dc3e0c7144e.png)

**The function:**
```delphi
function TChatCallForm.EdgeConsoleLog(const sender: ICoreWebView2; const args: ICoreWebView2DevToolsProtocolEventReceivedEventArgs): HResult;
var
  strJson   : PWideChar;
  js        : TJSONObject;
  jsMessage : TJSONObject;
  strLevel  : String;
  nIndex    : Integer;
begin
  if args.Get_ParameterObjectAsJson(strJson) = 0 then
    begin
      js := TJSONObject(TJSONObject.ParseJSONValue(strJson));

      if js.Get('message') <> nil then
        begin
          jsMessage := TJSONObject(js.Get('message').JsonValue);
          strLevel  := jsMessage.GetValue<string>('level');

          if strLevel = 'log' then
            AppendLogChat('TChatCallForm.EdgeConsoleLog: ' + m_tctType.ToString + ' | ' + jsMessage.GetValue<string>('text'))
          else if strLevel = 'error' then
            AppendLogChat('TChatCallForm.EdgeConsoleLog: ' + m_tctType.ToString + ' | [Error] | ' + jsMessage.GetValue<string>('text') + ' | ' + jsMessage.GetValue<string>('url') + ' line: ' + jsMessage.GetValue<string>('line'))
          else if g_LicenseManager.IsDeveloper then
            AppendLogChat('TChatCallForm.EdgeConsoleLog: ' + m_tctType.ToString + ' | [' + strLevel + '] | ' + jsMessage.GetValue<string>('text') + ' | ' + jsMessage.GetValue<string>('url') + ' line: ' + jsMessage.GetValue<string>('line'))
        end
      else if js.Get('exceptionDetails') <> nil then
        begin
          var lstLog := GetExceptionLog(TJSONObject(js.Get('exceptionDetails').JsonValue));

          if lstLog.Count > 0 then
            begin
              AppendLogChat('TChatCallForm.EdgeConsoleLog: ' + m_tctType.ToString + ' | [Error] | ' + lstLog[0]);

              for nIndex := 1 to lstLog.Count - 1 do
                AppendLogChat(lstLog[nIndex]);
            end;

          lstLog.Free;
        end;

      js.Free;
    end;

  Result := 0;
end;
```
I ran PasDoc inside Embarcadero's IDE with the following parameters: 
`-S C:\Users\lduarte\Desktop\Trabalho\PasDoc\sources.txt --Output PasDoc --Title "PasDoc" --implementation-comments=join --use-tipue-search --write-uses-list`
Being sources.txt just a single line containing:
`C:\Users\lduarte\Desktop\Trabalho\PasDoc\profit4_dev\source\Chat\Streaming\ChatCallFormU.pas`

After emailing Michalis, I was advised that as a workaround I could "**disable parsing implementation section. By default PasDoc only parses unit 'interface', and this problem should not occur**". Even though that's a good solution, it doesn't fit me, since the project I'm currently working on has a big source code and almost every comment is made in the implementation section.

I'd like to thanks Michalis for his great and promptly support. More thant that, thanks him by his incredible contribution to the open source community.

**Comment by Fr0sT-Brutal** [comment]
Added special handling of this case, should be working fine

**Comment by LeoUpperThrower4** [comment]
That worked perfectly for me!
Thank you, Fr0sT

**Comment by michaliskambi** [comment]
Applied PR #130 from @Fr0sT-Brutal , thank you!

Tested that it works OK on the submitted testcase, I did

```
pasdoc chatcallformu.pas -implementation-comments=join --use-tipue-search --write-uses-list 
```

with attached file.
[chatcallformu.pas.txt](https://github.com/pasdoc/pasdoc/files/7739304/chatcallformu.pas.txt)
