### ISSUE TITLE
sorting integers in VT

### ISSUE THREAD

**Issue by attikov** [pasdoc/pasdoc#134]
Sorting the integer columns in the VT are sorted as a string. ty

Aehm, sorting the circular column does nothing.

**Comment by michaliskambi** [comment]
Sorry, I do not understand what you're saying. What are VT? What integer columns? What circular columns?

Please attach a screenshot and/or describe the problem better.

**Comment by attikov** [comment]
Hi, VT = VirtualTree's common acronym, it has some columns like Lines, Used By Units, Used Units etc... values are integer, then you have a Column called Circular, none of the above and I think none of them are sorting correctly if you press on the title.
🤷

**Comment by michaliskambi** [comment]
We're making PasDoc. We're not related with VirtualTreeview ( https://documentation.help/VirtualTreeview/ , https://www.jam-software.com/virtual-treeview , https://github.com/JAM-Software/Virtual-TreeView ), which I understand you refer to.

And Virtual Treeview documentation on https://documentation.help/VirtualTreeview/ does not seem to be generated by PasDoc, not even by some fork of it. We don't have an UI that you describe (we don't have a list with such columns, we don't have a word "circular" in whole PasDoc codebase).

I assume that things you describe are part of some VirtualTree UI. It seems you wanted to submit some issue to Virtual Treeview.

**Comment by attikov** [comment]
ups, wrong browser tab, my apologies ;) just delete the issue if you can.
