### ISSUE TITLE
Outdated FSF address

### ISSUE THREAD

**Issue by suve** [pasdoc/pasdoc#136]
The licence text states the FSF address as:
```
 Copyright (C) 1989, 1991 Free Software Foundation, Inc.
 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
```

The current address, as posted on [FSF's website](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html), is:
```
Copyright (C) 1989, 1991 Free Software Foundation, Inc.  
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
```

---

As a note, the license headers found in code files have the up-to-date address.
```
  You should have received a copy of the GNU General Public License
  along with "PasDoc"; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
  ```
I used `grep` on the repository and it looks like only the `LICENSE` file has the old address.

**Comment by michaliskambi** [comment]
Thank you! I updated the license, with the latest version from https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt , that fixes the address and has some other cosmetic updates.

We have a PR updating FSF address some time ago ( https://github.com/pasdoc/pasdoc/pull/4 ), but it seems the LICENSE file slipped from our grep command :)
