### ISSUE TITLE
Files with BOM raise errors when parsing

### ISSUE THREAD

**Issue by peardox** [pasdoc/pasdoc#140]
I've got some [delphi source](https://github.com/Embarcadero/python4delphi) I want to get some documentation on

When using the GUI it throws an error

> Starting Source File Parsing ...
> Now parsing file C:\DelphiComponents\python4delphi\Source\PythonEngine.pas...
> Error EPasDoc: Invalid character ("?", code 239) in Pascal input stream (at C:\DelphiComponents\python4delphi\Source\Definition.Inc(1)) while parsing unit PythonEngine.pas, continuing...
> ... 1 Source File(s) parsed

The error message is misleading - I started out looking for a ? :)

Then it struck me - the file has a BOM (Byte Order Mark) at the start which should be at a minimum ignored

**Comment by michaliskambi** [comment]
We had a few fixes to handle BOM (though not yet released).

The latest PasDoc, from snapshots ( https://pasdoc.github.io/DevelopmentSnapshots ) or from source (this repo :), https://github.com/pasdoc/pasdoc/ ) should work OK.

Testing indeed it is OK (i.e. it doesn't fail on BOM): 

```
$ ~pasdoc python4delphi/Source/PythonEngine.pas 
PasDoc 0.16.0 [2021-02-07|FPC 3.2.2|Linux|64]
Documentation generator for Pascal source

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Info[1]:    Starting Source File Parsing ...
Info[2]:    Now parsing file python4delphi/Source/PythonEngine.pas...
Warning[2]: Error EPasDoc: python4delphi/Source/PythonEngine.pas(66): reserved word "interface" expected but identifier "Error" found while parsing unit PythonEngine.pas, continuing...
Info[2]:    ... 1 Source File(s) parsed
Fatal Error: EPasDoc: At least one unit must have been successfully parsed to write docs
```

The GUI behaves the same,

![Zrzut ekranu z 2022-06-15 13-23-43](https://user-images.githubusercontent.com/1076978/173816020-e88a70ef-cf58-4597-8e0b-c0ecd8ac315a.png)

Note that `PythonEngine.pas` still fails to be parsed, this actually makes sense, as it contains code 

```
unit PythonEngine;
...
{$IFNDEF FPC}
  {$IFNDEF DELPHI2010_OR_HIGHER}
      Error! Delphi 2010 or higher is required!
  {$ENDIF}
{$ENDIF}
...
interface
```

... so naturally PasDoc also enters the _Error! Delphi 2010 or higher is required!_ clause. See https://pasdoc.github.io/ConditionalDefines for explanation -- by default PasDoc doesn't define any compiler/OS/CPU defines, as we don't know what set of defines are good for docs. The usual solution is to add `--define=PASDOC` and then change the above code to be ignored by `{$ifndef PASDOC}...` but of course you can choose a different approach (e.g. you can just pass `pasdoc --define=FPC` if you want PasDoc to pretend it is FPC, or pass `DELPHI2010_OR_HIGHER`).

**Comment by peardox** [comment]
Hmm

Using the GUI I defined...
DELPHI10_3
DELPHI2010_OR_HIGHER
DELPHIXE_OR_HIGHER
DELPHIXE2_OR_HIGHER
DELPHIXE3_OR_HIGHER
DELPHIXE4_OR_HIGHER
DELPHIXE5_OR_HIGHER
DELPHIXE6_OR_HIGHER
DELPHIXE7_OR_HIGHER
DELPHIXE8_OR_HIGHER
DELPHI10_OR_HIGHER
DELPHI10_1_OR_HIGHER
DELPHI10_2_OR_HIGHER
DELPHI10_3_OR_HIGHER
DELPHI10_4_OR_HIGHER
MSWINDOWS
CPU64
EXTENDED_RTTI
VER340

MSWINDOWS
DELPHI2010_OR_HIGHER

> Starting Source File Parsing ...
> Now parsing file C:\temp\pypas\python4delphi\Source\PythonEngine.pas...
> Error EPasDoc: Invalid character ("!", code 33) in Pascal input stream (at C:\temp\pypas\python4delphi\Source\PythonEngine.pas(66)) while parsing unit PythonEngine.pas, continuing...
> ... 1 Source File(s) parsed

I thought that would work (didn't)

Even added Error! to ignored markers

**Comment by michaliskambi** [comment]
Fixed (the 2nd problem about "!"), thanks!

Background: While we were skipping a piece of code (because of if/ifdef/ifndef condition), but were still assuming that between it is a set a valid Pascal tokens. So words like "Error", "Delphi" are OK, numbers like 2010 are OK, but exclamation mark (!) is just invalid in Pascal.

I added a logic to ignore invalid Pascal tokens in this case. When we skip, we're really only looking for next compiler directive, like `{$endif}`.

It's committed, soon snapshots on https://pasdoc.github.io/DevelopmentSnapshots will contain it too.

**Comment by peardox** [comment]
Thanks @michaliskambi 

I worked-around the issue with PythonEngine.pas simply by commenting the line out but not sure if it upset anything else so will re-run with new snap later

**Comment by Fr0sT-Brutal** [comment]
While the fix in PasDoc is sane, I'd recommend also creating an issue in that project with request to change plain text line with `{$message fatal '...'}`

**Comment by peardox** [comment]
> While the fix in PasDoc is sane, I'd recommend also creating an issue in that project with request to change plain text line with `{$message fatal '...'}`

Posted an issue in a relevant repo linked to this one

**Comment by peardox** [comment]
PasDoc provides a useful list of the methods, properties etc which is 100% better than the previous documentation (none)

I aim to retroactively add PasDoc comments to the source and hope the authors (four projects in this specific group of dependent libraries) will see the benefit of adding PasDoc compatability to their stuff.

All libraries except the main Python4Delphi are only a few weeks and relatively small so there is hope that the authours will adopt PasDoc.

**Comment by Fr0sT-Brutal** [comment]
The aim that deserves respect!
"Back comments" could be fixed by adding a special char "<" to minimize changes required. [ref](https://github.com/pasdoc/pasdoc/wiki/WhereToPlaceComments#-placing-comments-after-the-item)
Also check [here](https://github.com/pasdoc/pasdoc/wiki/CommandlineExamples) for some advanced features
