### ISSUE TITLE
Nested enums are displayed regardless of visibility

### ISSUE THREAD

**Issue by fourls** [pasdoc/pasdoc#158]
The visibility of nested types is usually respected, but that doesn't seem to be the case for enums.

Using default configuration, generating docs for the following unit results in `TPrivateInnerEnum` being documented in the output.

```pascal
unit MyUnit;

interface

type
  TOuterObject = class(TObject)
  private type
    TPrivateInnerEnum = (pieSecret, pieMoreSecret);
    TPrivateInnerObject = class(TObject)
    end;
  public type
    TPublicInnerEnum = (puePublic, pueSuperPublic);
    TPublicInnerObject = class(TObject)
    end;
  end;

implementation

end.
```

![image](https://user-images.githubusercontent.com/28214458/202960595-32835b9e-c98d-4084-81ea-2e934cfe1a72.png)

**Comment by michaliskambi** [comment]
Confirmed, thank you for the testcase and indeed -- `TPrivateInnerEnum` is present in the output, but it should not be.

PRs are welcome :) I mean I will try to look into it around the weekend, but I'm not reliable with a limited time :) But if anyone wants to take a look at this and submit PR, I would surely merge the fix.

**Comment by fourls** [comment]
Thanks, I'm happy to take a look - If I get around to it in the next few days I'll submit a PR.
