### ISSUE TITLE
[FEATURE REQUEST] Auto-assignment of comments after the item

### ISSUE THREAD

**Issue by Ma2xx** [pasdoc/pasdoc#16]
I'm trying to use PasDoc to create a documentation of an existing project with> 500,000 lines of code.
My problem is the rule of simple comments within a line of code.

Actually PasDoc use this definition regarding bei the Wiki "WhereToPlaceComments"

>`TMyClass = class`
>`   MyField: Integer; //< Description of MyField`
>`    procedure MyProc; //< Description of MyProc`
>`    property MyProp: Integer read MyField write MyField;`
>`      //< Description of MyProp`
>`end;`
> If you use a CommentMarker, the "<" character must be placed right after your chosen marker.

My suggestion is to change PasDoc to automatically accept comments at the end of a line of code as comment of the line itself and not as a comment of the following line.

This should be independed of any extra CommentMarker, because I would not check all existing code to place CommentMarker at line-comments.

Simple comments of a line with sourcecode are for the line itself.
Simple comments of a new line are always comments of the following line of code.

I think these rules will be more general for using PasDoc with standard source code.

As compromise I can imagine to add a new command feature to define "--marker-simplecomments=<". 
If "--marker-simplecomments=" (empty or not set) then the assignment of the simple comment depends on existing or not existing code at the beginning of line.

Thank you
Regards

**Comment by michaliskambi** [comment]
Hm, I agree, that seems like a reasonable feature. A command-line option like `--automatic-back-comments` would turn on the logic _"If a comment starts on a line where an identifier was declared, then assign this comment to that identifier, just like it had `<` at the beginning"_.

I would not add `--marker-simplecomments`. The "marker", when referred to by the PasDoc documentation, is something different than `<`. It's related to https://github.com/pasdoc/pasdoc/wiki/CommentMarker , and it applies (if defined) to all comments (back or forward).  There is no need to change "back comment indicator" to something else than `<`, so let's keep this simple.

I'm not sure when I'll have time to implement it, though. Patches are welcome, of course:)

**Comment by michaliskambi** [comment]
With many thanks to @Fr0sT-Brutal , this is now implemented :) The option is called `--auto-back-comments` , I added docs on https://github.com/pasdoc/pasdoc/wiki/AutoBackComments .

**Comment by michaliskambi** [comment]
P.S. A new PasDoc build, where you can test it, should be available shortly on http://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ .
