### ISSUE TITLE
Conditional uses

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#17]
Hello.

Please take a look at the following doc (notice `Windows` and `Posix.Errno` together sounds that something is wrong):

![image](https://user-images.githubusercontent.com/1456829/37869029-2a72565a-2f8f-11e8-9162-abacec705fe2.png)

it was generated from:

```pascal
[snip]

uses
{$IF DEFINED(MSWINDOWS)}
  Windows,
{$ELSEIF DEFINED(FPC) AND DEFINED(UNIX)}
  BaseUnix,
{$ELSEIF DEFINED(POSIX)}
  Posix.Errno,
{$ENDIF}
  SysUtils,
  libbrook,
  Marshalling,
  BrookHandledClasses;

[snip]
```

however, it depends on `IFDEF`s:

```pascal
...
{$IF DEFINED(MSWINDOWS)}
  Windows,
{$ELSEIF DEFINED(FPC) AND DEFINED(UNIX)}
  BaseUnix,
{$ELSEIF DEFINED(POSIX)}
  Posix.Errno,
{$ENDIF}
...
```
so I would like to remove them (system units) from my documentation.

I'm not sure if/how PasDoc handle situations like that. If we doesn't have such feature, this topic title should be edited to feature request. :smiley:

**Comment by michaliskambi** [comment]
You should see a warning in the console (visible also in GUI):

```
Warning[2]: Evaluating $if and $elseif conditions is not implemented, I'm simply assuming that "DEFINED(MSWINDOWS)" is true
```

As the warning says, PasDoc cannot yet handle expressions inside `$if`, so it cannot handle `{$if defined(xxx)}` or `{$if defined(xxx) or defined(yyy)}`. It assumes that whatever condition is specified, `{$if xxx}` is true.

Right now, PasDoc can only handle simpler `{$ifdef xxx}`.

So this is a feature request :) I'll try to hack a quick parsing of simple expressions next week, this should be fun and easy.

Also, looking closer, I see that the `{$elseif ...}` is not handled at all. This is why both `Windows`, `BaseUnix`, `Posix.Errno` and up being parsed. So, this is a (related) bug. I'll handle it too:)

**Comment by michaliskambi** [comment]
Sorry for the delay -- I have this on my TODO list, but I just did not find time yet.

In the meantime, if you would like to tacke it (the modification should be mostly in `pasdoc/source/component/PasDoc_Scanner.pas`, search there for how if/ifdef/etc are handled), I would welcome a pull request :) But if not, I'll try to handle it -- hopefully within ~2 weeks.

**Comment by michaliskambi** [comment]
(Ups, closed by accident.)

**Comment by michaliskambi** [comment]
Done! We now correctly handle `$if`, `$elseif`, and various expressions inside. The testcase is on https://github.com/pasdoc/pasdoc/blob/master/tests/testcases/ok_if_expressions.pas .

Sorry that it took me much longer than promised.

To test it, you can compile yourself PasDoc from GitHub https://github.com/pasdoc/pasdoc/ or take a precompiled version from snapshots: http://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ .
