### ISSUE TITLE
SimpleXML: Visibility info missing for all elements

### ISSUE THREAD

**Issue by andre2007** [pasdoc/pasdoc#176]
All elements in SimpleXML output misses the visibility info like e.g. properties 
{
    "_default_in_class": "False",
    "_default_value": "",
    "_indexdecl": "",
    "_name": "Scale",
    "_nodefault": "False",
    "_reader": "",
    "_stored": "",
    "_type": "",
    "_writer": ""
}

 Could you add the visibility info (public, protected, published) for all elements (variables, methods, properties, ...)? Thanks.

**Comment by andre2007** [comment]
I just noticed, I need to include the protected symbols also for another use case. Therefore my issue would be solved if you could add the "visibility" information (from TPasItem) of the different artifacts (routines/properties/...) into the SimpleXML output. This would be great.

**Comment by andre2007** [comment]
https://github.com/pasdoc/pasdoc/pull/178

**Comment by michaliskambi** [comment]
I understand this can be closed now :)
