### ISSUE TITLE
Cannot parse system.pas due to [Volatile] and [HPPGEN...]

### ISSUE THREAD

**Issue by andre2007** [pasdoc/pasdoc#179]
Delphi system.pas contains the code below.
Parser stops with error message: `identifier expected but symbol "[" ..` due to `[Volatile]` and `[HPPGEN`

``` delphi
    var
      [Volatile] FLockCount: Integer;
```

``` delphi
  IEnumerator<T> = interface(IEnumerator)
    [HPPGEN('virtual T __fastcall GetCurrentT(void) = 0')]
    function GetCurrent: T;
    [HPPGEN('__property T Current = {read=GetCurrentT}')]
    property Current: T read GetCurrent;
  end;
```

**Comment by michaliskambi** [comment]
Fixed, thank you!

This spiralled into some related interesting fixes :)

1. We improve our support to distinguish that you can use the same name for generic and non-generic classes/interfaces, i.e.

    ```
    TMyClass = class
    end;
    TMyClass<T> = class
    end;
    ```

    These 2 classes are distinct, and this compiles in FPC.

    That is also why we can use I guess both `TObjectList<T>` and non-generic `TObjectList`, without one obscuring another. I.e. the test below compiles OK (tested with FPC 3.2.2 now, but I guess it is the same on Delphi):

    ```delphi
    {$ifdef FPC} {$mode delphi} {$endif}
    uses Contnrs, Generics.Collections;
    var
      L1: TObjectList; // uses list from Contnrs
      L2: TObjectList<TObject>; // uses list from Generics.Collections
    begin
    end.
    ```

    PasDoc support for it is not perfect, but at least you can now do this, and `TMyClass` and `TMyClass<T>` will be in different HTML files.

2. We now secure from sneaky declarations causing loops:

    `TMyClass = class(TMyClass)`

    This will no longer cause PasDoc to just hang. It's not a fool-proof solution, but at least it's a start, we detect trivial loop (without wreaking havoc over PasDoc codebase that iterates over ancestors in many places).

    As it happens, it also workarounds our imperfect support for AD 1. So

    `TMyClass<T> = class(TMyClass)`

    (which is valid) will now cause a warning:

    ```
    Warning[1]: Class or interface refers to itself as ancestor, ignoring to avoid infinite loops when traversing hierarchy: TMyClass
    ```

    ... but at least the rest of processing will work, instead of entering an infinite loop as before.

3. Finally, we improve custom attribute support, to allow them in all places.

**Comment by andre2007** [comment]
Thanks a lot for your help 👍
