### ISSUE TITLE
Faulty support for @cvs $Date

### ISSUE THREAD

**Issue by chrisv5** [pasdoc/pasdoc#18]
There are two issues here. First, fixed length format (the one with the double colon at the beginning and #$ at the end) is not recognized.

Second, in the floating format, while it is recognized, the text literal UTC is wrongly added to the time stamp, which is wrong. SVN documentation clearly states:

"Unlike the Id keyword, which uses UTC, the Date keyword displays dates using the local time zone"

**Comment by chrisv5** [comment]
There are two issues here. First, fixed length format (the one with the double colon at the beginning and #$ at the end) is not recognized.

Second, in the floating format, while it is recognized, the text literal UTC is wrongly added to the time stamp, which is wrong. SVN documentation clearly states:

"Unlike the Id keyword, which uses UTC, the Date keyword displays dates using the local time zone"

**Comment by michaliskambi** [comment]
Can you put here a sample code with the dates which PasDoc interprets wrong?

This would help me to fix this quickly:) I admit I didn't use $Date since a long time. Thanks!

**Comment by chrisv5** [comment]
No problem at all. This unit header:

    {** Table class for purchase order lines.
    
      @author Christian Vitroler
      @author Lukas Vitroler
      @created 05 Sep 2014
      @cvs $Date:: 2018-06-02 11:34:12 #$ }

yields as result:

    Description
    Table class for purchase order lines.
    @(cvs$Date:: 2018-06-02 11:34:12 #$)
    .
    .
    .
    Authors
        Christian Vitroler
        Lukas Vitroler
    Created
    05 Sep 2014

When I remove one of the colons, I get this:

    Created
    05 Sep 2014 
    Authors
        Christian Vitroler
        Lukas Vitroler
    Created
    05 Sep 2014
    Last Modified
    2018-06-02 11:34:12 UTC

**Comment by michaliskambi** [comment]
Fixed, thanks for the report! To test it, you can download PasDoc from http://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ (it should automatically update in ~15 minutes to contain the latest fix), or get PasDoc source code from https://github.com/pasdoc/pasdoc/ and compile it yourself.

**Comment by chrisv5** [comment]
Works like a charm! Thank you for the lightning fast support, you are awesome. Is there any donation page?

**Comment by michaliskambi** [comment]
If you'd like to help me with what I'm doing (PasDoc, [Castle Game Engine](https://castle-engine.io/), [Modern Object Pascal Introduction for Programmers](https://castle-engine.io/modern_pascal_introduction.html)), you can donate through https://www.patreon.com/castleengine or any method mentioned on https://castle-engine.io/donate_other.php . Thank you!
