### ISSUE TITLE
Feature request for GUI (support for --auto-link-exclude option)

### ISSUE THREAD

**Issue by chrisv5** [pasdoc/pasdoc#19]
It seems like, there is no support in PasDoc GUI (at least not in the latest release, 0.15.0) for this rather useful feature. Without this, the option is --autoLink (which does have a GUI equivalent) is rather annoying. Common names as member names in records or classes are becoming a real PITA in the documentation.

**Comment by michaliskambi** [comment]
Agreed. I'll add it soon:)

**Comment by chrisv5** [comment]
While you are at it, you might also add a line for --description on the custom files tab.  Generally, I believe, the GUI should offer all options which are available at the command line. Or at least add a field where one can add any arbitrary command line parameters which will be appended upon invocation of pasdoc.exe.

**Comment by michaliskambi** [comment]
Sure, I'll add the functionality of --description to the GUI.

Indeed, the GUI is supposed to offer the same features as command-line. If anything is missing, it's a bug we want to fix:)

Note that GUI does *not* work by calling command-line pasdoc. It does not pass the options through command-line parameters. Instead the command-line and GUI share a common code (source/component/ subdirectory in repository).

**Comment by chrisv5** [comment]
May I humbly inquire what time range is on your mind for adding those features?

**Comment by michaliskambi** [comment]
They are trivial, so the time range is "ASAP" :) I'll do them definitely this week.

**Comment by michaliskambi** [comment]
Done:) I promised "this week" :)

There's a new separate page for "Auto Linking". The external descriptions file can be specified on the "Custom Files" page.

As always, you can test the result either by compiling PasDoc from GitHub yourself ( https://github.com/pasdoc/pasdoc/ ), or you can get the snapshot from http://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ . Enjoy:)

**Comment by chrisv5** [comment]
Indeed, this week :-) Perfect timing! I already utilized both features and they work like a charm. Thanks a lot for the great service!
