### ISSUE TITLE
Parser has problems with include file:  Evaluating "declared" function for $if / $elseif not implemented

### ISSUE THREAD

**Issue by MHumm** [pasdoc/pasdoc#196]
When trying to use your tool (the GUI variant) to generate the documentation for this here:

[https://github.com/MHumm/DelphiEncryptionCompendium](https://github.com/MHumm/DelphiEncryptionCompendium)

To be precise: all the .pas files in the Source subdirectory. It only creates documentation for three of them reporting multiple times 
"Cannot evaluate this $if / $elseif condition, assuming that "DECLARED(FireMonkeyVersion)" is true. Error message is: Evaluating "declared" function for $if / $elseif not implemented"

**Comment by michaliskambi** [comment]
The warning is indeed exactly true. Evaluating `declared(xxx)` is not implemented in PasDoc. 

It would be quite hard to implement `declared(xxx)` handling. Unlike a real compiler, PasDoc parses the interface (and implementation, if you ask for it) without having to really know the used units. We also don't read information about previously parsed units interface from files like PPU / DCU. And without this knowledge, and precise (including all used units, including standard units included in FPC / Delphi) knowledge what is declared in all units, we cannot make a valid implementation of `declared(xxx)`. 

I'm afraid it is unlikely we'll implement `declared(xxx)` handling in PasDoc anytime soon. I will close this as `wontfix` -- to "manage expectations", we don't want to give false impression to users that this is a feature/fix that may come soon.

A workaround is easy, see https://pasdoc.github.io/ConditionalDefines :

You can have a define like `PASDOC`, defined only by PasDoc, and avoid the `DECLARED(FireMonkeyVersion)` check in this case. Like

```delphi
// Do not check declared(FireMonkeyVersion) in PasDoc, as PasDoc cannot evaluate "declared"
{$ifndef PASDOC}
  {$if declared(FireMonkeyVersion)}
  procedure DoSomethingFmxSpecific;
  {$endif}
{$endif}
```
