### ISSUE TITLE
hhc.exe

### ISSUE THREAD

**Issue by peardox** [pasdoc/pasdoc#197]
M$ no longer have a link to this but to make HTML: Help you  still need it

There are a few unofficial archives - see https://learn.microsoft.com/en-us/answers/questions/265752/htmlhelp-workshop-download-for-chm-compiler-instal

This should be updated in the PasDoc docs...

**Comment by michaliskambi** [comment]
Thank you! Updated https://pasdoc.github.io/HtmlHelp to link to working downloads.
