### ISSUE TITLE
[FEATURE REQUEST] More custom files than just introduction and conclusion

### ISSUE THREAD

**Issue by alexmerkel** [pasdoc/pasdoc#20]
I would love to be able to add additional custom files to my documentation, not just an introduction and a conclusion.
Is that already possible and I'm just missing something? If not, I would love to see this feature added.

**Comment by michaliskambi** [comment]
For now, you are limited to only introduction and/or conclusion. But the underlying system is indeed much more general, it should be possible to allow you to define any number of "additional documents" easily. Having only introduction and/or conclusion could be just a special case then.

So, it should be easy to implement it.. That said, I don't know when I'll have time to do it, unfortunately. Pull requests for this would be welcome :)

**Comment by michaliskambi** [comment]
Closed by #21 .
