### ISSUE TITLE
[FEATURE REQUEST] Support & prefix.

### ISSUE THREAD

**Issue by myarmor** [pasdoc/pasdoc#28]
Please support/allow the & prefix.
The & prefix is used when you want to use a reserved word as a name for something.
Pasdoc currently seem to abort parsing f the containing file when this happens.

[Documentation here](http://docwiki.embarcadero.com/RADStudio/Tokyo/en/Fundamental_Syntactic_Elements_(Delphi)#Extended_Identifiers)

Example usage of the & prefix:
`
{$AppType Console}
program test;
uses
System.Classes,System.SysUtils;

type
TTest=class
  class var
    &begin : Integer;
  class constructor Create;
  class function &end : Integer;
end;

class constructor TTest.Create;
begin
  &begin:=100;
end;

class function TTest.&end : Integer;
begin
  Result:=TTest.begin;
end;

var
&var : Integer; // dummy showing a global variable with a reserved name.
begin
  &var:=15;
   WriteLn(Format('Test=%d var=%d',[TTest.end,&var])); // Notice the _lack_ of & for TTest.end.
end.`

Running this dummy will output "Test=100 var=15".

**Comment by michaliskambi** [comment]
Thanks for the report! This was easy, so I just implemented it :)

To try the fix:
- You can get the latest build from https://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ .
- Or you can get and recompile PasDoc from https://github.com/pasdoc/pasdoc/ on your own.
