### ISSUE TITLE
syntax error on dot-file by classed, that use a dot within the name

### ISSUE THREAD

**Issue by flashpixx** [pasdoc/pasdoc#29]
The graphiz dot-file export creates an error on class names with a dot inside the name:

Delphi source: ` MyThread = class(classes.tthread)`
wrong pasdoc dot-result: `DiGraph Classes { MyThread -> classes.tthread }`
correct dot-solution: `DiGraph Classes { MyThread -> "classes.tthread" }`

So if an dot is within the name on the right side, double-quotes must be set

And with that it should be helpful if dot is execute by PasDoc directly and put on HTML export a SVG file as menu item within the documentation

**Comment by michaliskambi** [comment]
Thanks for the report!

I trivially fixed the class name to be inside double-quotes in GraphViz output. (To be simple and safe, I did it for all class names, not only ones on the right side of the `->`).

More improvements to GraphViz (automatically calling the `dot`, from both command-line and GUI pasdoc versions, and using SVG), are indeed desired :) They are recorded at various places ( https://github.com/pasdoc/pasdoc/wiki/WantedFeatures -- my old comments there mention SVG and direct running). So this issue can be closed.

**Comment by michaliskambi** [comment]
P.S. The fix is in the PasDoc GitHub sources, you can also use the "snapshot" that should make a new version in ~15 minutes on http://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ .

**Comment by flashpixx** [comment]
Thanks for that quick fix, I have added my current [Boostrap solution](https://github.com/pasdoc/pasdoc/files/2848539/htmltemplate.zip) to this issue a 'logo.png' and a 'favicon.ico' file must be added. See #31 for the usage

**Comment by flashpixx** [comment]
The files will now generated, but I have added `--link-gv-uses svg` and `--link-gv-classes svg` both dot files exist and I can compile it manually with the command `dot -Tsvg file.dot -o file.svg` but only the classes item is added to the HTML navigation. I get during documentation generating a lot warnings and some classes cannot be parsed, but the dot run should be executed everytime if the dot files can be generated and if dot does not generate an error the menu link should be set
