### ISSUE TITLE
[question] How do I declare a function using "@link(foo())" instead of "@link(foo)"?

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#33]
Hello.

I've used declarations like `@link(Sagui.Malloc)` to reference functions, however, I would like to declare something like `@link(Sagui.Malloc())`, but when ending the content by `()` it generates "`UNKNOWN`" instead of `Sagui.Malloc()`.

Thank you!

**Comment by michaliskambi** [comment]
PasDoc indeed cannot resolve the `@link(Sagui.Malloc())` for now.

It will in the future. To support linking to different overloads of the same function, we will support syntax like `@link(Sagui.Malloc())` (link to parameter-less function) or `@link(Sagui.Malloc(Integer,String))` (link to overloaded version that takes 2 arguments, Integer and String). However, this is not done for now. (It is mentioned in https://github.com/pasdoc/pasdoc/wiki/ToDo , as https://github.com/pasdoc/pasdoc/wiki/ToDoOverloadingLinking ).

For now, simply use the `@link` tag feature to specify optional "display text", https://github.com/pasdoc/pasdoc/wiki/LinkTag . Like this: `@link(Sagui.Malloc Sagui.Malloc())`. I know, it looks somewhat ugly and repetitive, but it works:)

**Comment by silvioprog** [comment]
Thanks a lot for answering and sharing the workaround for now and related references. I'm going to take a look at them. Thanks again! :-)
