### ISSUE TITLE
[feature request] @note/@warning

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#34]
Hello.

It would be nice to add support for something like Doxygen's [`\note`](http://www.doxygen.nl/manual/commands.html#cmdnote) and [`\warning`](http://www.doxygen.nl/manual/commands.html#cmdwarning) commands.

Example at bottom of this picture:

[![image](https://user-images.githubusercontent.com/1456829/55270919-d76dc700-5283-11e9-9900-d9f184a3c5eb.png)](https://risoflora.github.io/libsagui-docs/group__sg__httpsrv.html#gaf1af6a4ba7a05e73c71ce9e82c4aae9a)

**Comment by michaliskambi** [comment]
Fixed by new `@warning` and `@note` ,  https://github.com/pasdoc/pasdoc/wiki/NoteAndWarningTags , thanks to @Bi0T1N !
