### ISSUE TITLE
[feature request] @url tag

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#36]
Hello.

It would be nice to specify external URLs, something like `@url(<URL>)` or `@url(Some description <URL>)`, e.g: `@url(https://www.gnutls.org)` or `@url(GnuTLS library https://www.gnutls.org)`.

Possible parsing logic:

- If the content starts with `http://` or `https://`, it is an external URL, so it is generated as simple tag `<a href="http://some-url"></a>`.
- If the content start with any word or multiple words separated by empty space and is followed by `http://` or `https://` after the empty space, it is a description followed by an external URL, so it is generated by a full tag `<a href="http://some-url">Some description</a>`.
- If a content doesn't contains any `http://`/`https://`, it is put as it is, i.e., no tag `<a>`.
- PasDoc doesn't checks or validates any external URL, it just puts it to the generated `<a>`.

Thank you!

**Comment by michaliskambi** [comment]
I'm cool with this idea, although it should work simpler, following existing PasDoc `ExtractFirstWord` logic (uses e.g. with `@link`). So the URL would be just the first "word" inside `@url(....)`. So you would write `@url(https://www.gnutls.org GnuTLS library)`, this is consistent with `@link`.

Pull requests are welcome :) We already can display URLs, although right now they are just detected inline, you cannot specify an alternative "dusplay text" for them.

**Comment by michaliskambi** [comment]
Closed by #99 , documented on https://github.com/pasdoc/pasdoc/wiki/UrlTag .
