### ISSUE TITLE
Missing translation of "See Also" in Portuguese

### ISSUE THREAD

**Issue by carlosbfeitozafilho** [pasdoc/pasdoc#37]
Well the title is all I need to say :)

**Comment by michaliskambi** [comment]
Would you like to submit a translation? :) I'm not a Portugese speaker, and I don't want to use auto-translate (as it often produces weird results).

Our translation files are in https://github.com/pasdoc/pasdoc/tree/master/source/component/lang . If you want to create a new translation, you can start by copying `PasDoc_Languages_Template_New_Language.inc`. If you want to edit existing one, go ahead and edit e.g. `PasDoc_Languages_Brasilian_utf8.inc` . You can submit the resulting file as [GitHub pull request](https://help.github.com/en/articles/about-pull-requests) or just attach the file here.

**Comment by carlosbfeitozafilho** [comment]
Hi @michaliskambi

Really I can help on this! Thank you

PS.: When I submit or create a pull request, when the new version wil be
released?

>

**Comment by carlosbfeitozafilho** [comment]
Another question:

Which branch I must use?

**Comment by michaliskambi** [comment]
After a new commit, you will be able to download new version immediately from https://github.com/pasdoc/pasdoc/wiki/DevelopmentSnapshots ( http://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ ). I cannot yet say when the new "official, stable" version will be released (above links point to "unstable" version).

Use the `master` branch.

**Comment by carlosbfeitozafilho** [comment]
Thank You!

>

**Comment by carlosbfeitozafilho** [comment]
Hi! I'm trying to push the code but I do not have permission to this. How to get permission to push? I've done the translation and included some files necessary to compile on Delphi Community Tokyo.

**Comment by michaliskambi** [comment]
You do not have permissions to push to the main PasDoc repository, indeed. Instead I would ask to submit modifications using the GitHub "pull requests". This way you do not need any permissions but you can still work comfortably, and I review the modifications before "accepting" them. See the documentation on https://help.github.com/en/articles/about-pull-requests . 

Short instructions:

- "Fork" the pasdoc repository (using the appropriate button on the GitHub webpage of https://github.com/pasdoc/pasdoc/  ). In effect you will see a copy (this is called a "fork") of PasDoc repository within your own profile, https://github.com/carlosbfeitozafilho . It will have a link like `https://github.com/carlosbfeitozafilho/pasdoc` .

- Using your favorite GIT client, clone your new repository (`https://github.com/carlosbfeitozafilho/pasdoc`), and commit to it and push to it your modifications. You automatically have permissions to push to your own "forked" pasdoc copy.

- Once you're done (you consider the work finished and ready for review), create a pull request clicking on https://github.com/pasdoc/pasdoc/pulls .
 
- Then I review the modifications, and I accept them using the "Merge" button, and this way your commits "land" in the main PasDoc repository on https://github.com/pasdoc/pasdoc/ .

**Comment by carlosbfeitozafilho** [comment]
Ahh I'll do it tomorrow. I do not like git, so, this was a problem to me, however now I know what to do. Thank you

**Comment by carlosbfeitozafilho** [comment]
Hi!

It's done. I hope you accept it and like my work :)

**Comment by michaliskambi** [comment]
Yes, it's cool. Sorry for the delay, it was busy beginning of the week :) Thank you for the work! 

I submitted a minor change request in https://github.com/pasdoc/pasdoc/pull/38 (I would prefer to use one `lib` subdirectory instead of multiple `dcu` subdirectories). 

I'm closing this issue -- further discussion can take place in https://github.com/pasdoc/pasdoc/pull/38.
