### ISSUE TITLE
[bug] `longcode` without additional markers

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [pasdoc/pasdoc#42]
Docs say that `longcode` allows using without additional markers. Nevertheless, if we try it, it generates weird output:
```pascal
(*
  @longcode(
    { Some multiline 
      comment }
  )
*)

unit ok_longcode_comment;

interface

implementation

end.
```
Result:
```
@(longcode
    { Some multiline 
      comment }
  )
```
I see this content is constructed in `TTagManager.CoreExecute` and changed in `TDocGenerator.HandleLongCodeTag` but I'm not sure why `TTagManager.CoreExecute` creates such weird value.

**Comment by michaliskambi** [comment]
Thanks for reporting, found it :) Fixed.
