### ISSUE TITLE
[suggestion] Do not generate All*.html files if there's nothing to write there

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [pasdoc/pasdoc#59]
Now `All*.html` files are generated even if there's nothing to write there so they contain just "The units do not contain any *" message. I suggest to not generate html's in such cases thus removing useless files and reducing visual noise in generated docs. Moreover, this would significantly reduce the number of files in repo because most of testcases are very short.

**Comment by michaliskambi** [comment]
A small issue I see with this change is that it would make cache of HTML documentation ( https://github.com/pasdoc/pasdoc/wiki/CacheOption ) sometimes not OK. We don't write HTML output if a unit didn't change and the cache is used. So each generated page will assume that the list that was empty stays empty, and non-empty list stays non-empty. 

To be more precise, this is the interesting scenario:

- Prepare documentation for two units, A and B. Neither of them has any constants. Run PasDoc with `--cache-dir`.
- So the `AllConstants.html` file will not be generated at all, and `A.html` and `B.html` will not contain a link "Constants" in the sidebar.
- Now change unit B, adding there a new constant.
- Generate documentation for A and B again, again with the same `--cache-dir`.
- In effect, `AllConstants.html` will be generated, and new `B.html` will link to it. But `A.html` will remain unchanged, and not link to it.

A simple solution would be to avoid this mechanism (always generate `All*.html` files and link to them) when `--cache-dir` is used.

There remains a question how useful it is :) It would be helpful to simplify output in PasDoc `tests/testcases_output`, but is it really very useful for real-world documentation? I mean, who writes code with zero classes, or zero other types, or zero constants? :)

**Comment by Fr0sT-Brutal** [comment]
Huh, I've never had caching work (not that I tried hard though) so I missed that point. Well, question of how useful it is also reasonable :)

**Comment by Fr0sT-Brutal** [comment]
Doesn't worth the efforts indeed
