### ISSUE TITLE
Handle @raises(exception) without auto-link warnings

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [pasdoc/pasdoc#68]
Tag `@raises` requires exception class as 1st word but it's rather frequent to have general Exception there. So auto-linking tries to search for `exception` identifier and produces warning. Maybe we should process the very word `Exception` as standard identifier and not try to auto-link it.

**Comment by michaliskambi** [comment]
I also sometimes raise e.g. `EConvertError` when my routine uses StrToInt internally. So I would prefer more general mechanism, not hardcoding `Exception` :)

A proposal:

- First check is the class name found in user code, if not...

- Then search for it in our ExternalClassHierarchy. We have a build-in list of hierarchy in `source/component/external_class_hierarchy.txt` (included automatically in PasDoc binary), and user can customize it by https://github.com/pasdoc/pasdoc/wiki/ExternalClassHierarchy . It already contains a number of standard exception classes, like `Exception`, `EConvertError`, `EInvalidOp`...

- If the class is found in `ExternalClassHierarchy` , then we don't make a warning when it doesn't exist (e.g.  we emit only an information with level like 6, so user will not see it by default as default verbosity is  2 as far as I recall).

- I think this will require changing `TDocGenerator.SearchLink`, currently it gets parameter `WarningIfLinkNotFound: boolean`. This parameter could change to `ActionWhenLinkNotFound: TActionWhenLinkNotFound` where `TActionWhenLinkNotFound` is enum = 
```
(awWarning, //< always make a warning, 
awIgnore,  //< ignore without any warning/info, 
awWarningIfNotExternal //< like awWarning, but if class exists on ExternalClassHierarchy then we make an info message with verbosity 6 instead of warning
)
```

`WriteParamsOrRaises` in HTML generator uses `SearchLink`, and would call `SearchLink` with `awWarningIfNotExternal`.

**Comment by Fr0sT-Brutal** [comment]
Yeah, sounds very nice!
