### ISSUE TITLE
Get procedure and functions code

### ISSUE THREAD

**Issue by bibilo** [pasdoc/pasdoc#7]
Hi There . sorry for submit my question as an issue.
Can i get procedure and functions code as their name  ?
did you implant this ? 
sorry for my bad english
best regards

**Comment by michaliskambi** [comment]
Right now, PasDoc does not parse the implementation section. See also https://github.com/pasdoc/pasdoc/wiki/WantedFeaturesParsingImplementation . So if you're interested in showing the function/procedure implementation in PasDoc -> this is unfortunately not possible now, as PasDoc doesn't even know your implementation.

**Comment by michaliskambi** [comment]
P.S. It is possible that I misunderstood your question, I was not sure what do you mean by _"get procedure and functions code as their name"_. If so, please excuse me, and reopen this with a clarification of your question :)

**Comment by bibilo** [comment]
for example this is my procedure
```
procedure testing;
begin
showmessage("hello");
end;
```

i want give 'testing' to a function and function return `showmessage("hello");`
@michaliskambi

**Comment by michaliskambi** [comment]
OK, thanks for clarifying. Unfortunately, this is not possible -- PasDoc does not parse the implementation section, so is has no way to see the `showmessage("hello");`.

Consider using fcl-passrc, a Pascal parser included in FPC, for this: http://wiki.freepascal.org/fcl-passrc .
