### ISSUE TITLE
support odf file

### ISSUE THREAD

**Issue by Reaper10** [pasdoc/pasdoc#73]
can someone add support odf file?

**Comment by michaliskambi** [comment]
It would be nice, but ODF (while open and popular https://en.wikipedia.org/wiki/OpenDocument ) is still rather complex file format.

I would suggest to rather implement DocBook, and then from DocBook one has a myriad conversion options, e.g. to ODF ( http://open.comsultia.com/docbook2odf/ ). DocBook opens a door to many other output formats :)

**Comment by Fr0sT-Brutal** [comment]
This probably could be achieved by converting a Latex output to desired format

**Comment by michaliskambi** [comment]
I was searching the Internet about LaTeX -> ODF converters, but found nothing that looks promising. 

There is one online tool that promises that, but it's unknown what application they use underneath (and if it really works :) ).

Some list of LaTeX conversions is on https://en.wikibooks.org/wiki/LaTeX/Export_To_Other_Formats , but nothing to ODF. It's probably possible to convert LaTeX -> RTF -> then ODF, the last step could be done in any open-source Word-like application I suppose.

**Comment by Fr0sT-Brutal** [comment]
I looked at DocBook specs... and though it doesn't worth the efforts :) Honestly I hardly could understand the need of non-structured formats (ODT, single HTML, even Latex itself) applied to source docs which is divided into levels (unit>type/constant/class>members) by definition. The only such format that has sense for me is Markdown - at least it could be put in the docs of a repo.

Probably we could implement one-page HTML output that further could be read or converted by thousands of apps to thousands of formats.

**Comment by michaliskambi** [comment]
I would still say that DocBook is best to be converted into further output formats. It's just made for this -- converting DocBook to other formats usually yields good results, as DocBook has the semantic (not only presentation) information to do it right. And it can made PDF, ODF, or single-page HTML, or multiple-page HTML (although this would be much worse than our "native" HTML output) etc.

The usefulness of presenting documentation in a single big file is another matter. Indeed it just doesn't make sense sometimes. E.g. for _Castle Game Engine_, a few years ago, I produced an API documentation with 160+ pages. It was pretty useless -- I mean HTML output was much much better to read / navigate / search on a computer. I don't believe anyone ever printed the API documentation of _Castle Game Engine_ on paper (I hope not, for the trees :) ).

But this is something for user to decide. Some people have much smaller documentation, and it may make sense. There *was* some rationale behind providing LaTeX output after all long time ago :), even if that was before any  of us was working on PasDoc.

**Comment by Fr0sT-Brutal** [comment]
Yep, surely DocBook is very good and nice but it has one big drawback - it is damn over-featured ))) at least I even couldn't find a simple human-readable overview of its main features with samples. So I strongly doubt it would ever be implemented unless one of us (or maybe one more enthusiastic guy or even girl!) needs it so much and decides to spend plenty of time on this.

**Comment by Reaper10** [comment]
this mite help https://forum.lazarus.freepascal.org/index.php?topic=21868.0
