### ISSUE TITLE
Comment on first const not handle correctly

### ISSUE THREAD

**Issue by jdelauney** [pasdoc/pasdoc#75]
Hi in this sample for example : 

>   //{$IFDEF UNIX}
>   // BaseUnix, Unix, Unixutil, linux
>   //  {$IFDEF X11_SUPPORT}
>   //   ,xlib
>   //  {$ENDIF}
>   //  {$IFDEF LCLCarbon}
>   //   MacOSAll
>   //  {$ENDIF}
>   //{$ENDIF};
> 
> //==============================================================================
> 
> 
> const
>  // Langue utilisée par défaut
>  cDefaultLanguage : String = 'FR';  

The output take all comment above the const

> {$IFDEF UNIX} BaseUnix, Unix, Unixutil, linux {$IFDEF X11_SUPPORT} ,xlib {$ENDIF} {$IFDEF LCLCarbon} MacOSAll {$ENDIF} {$ENDIF}; ============================================================================== Langue utilisée par défaut

the only solution is to use //< on the first const

Cheers

**Comment by jdelauney** [comment]
It's very strange in another unit i have

```
//==============================================================================
{$mode objfpc}{$H+}
{$i ..\bzscene_options.inc}
//==============================================================================

interface

uses
  Classes, SysUtils, LCLIntf, LCLType
  {$IFDEF WINDOWS}
  ,windows
  {$ENDIF}
  {$IFDEF UNIX}
  ,BaseUnix
  {$ENDIF};
```

All work fine

for info the header of all my units are the same, so...??????

Cheers

**Comment by michaliskambi** [comment]
All the `//` comments above the identifier are glued into one comment. See https://github.com/pasdoc/pasdoc/wiki/WhereToPlaceComments - section _"Glueing single-line comments_".

So another solution is also to use `{ xxx }` comment, e.g. this will work naturally:

```
const
{ Langue utilisée par défaut }
cDefaultLanguage : String = 'FR';
```

... and it will not matter what other comments were above.

Note: I agree that we should probably break the glueing on `const` keyword... but this could lead to a complicated logic (complicated to implement, and to document), if start to be "smart" and stop "glueing  of the // comments" at some points. So for now, we don't do it.

**Comment by Fr0sT-Brutal** [comment]
Yes, this behavior could be pretty confusing. Another way to avoid glueing is `{ }` comment (note space inside) placed after all non-relevant `//` comments

**Comment by jdelauney** [comment]
Ok thanks i didn't read this part of documentation so, it's not a big problem, using marker or { } is ok and enought for me 👍 

Thanks
