### ISSUE TITLE
Fountain syntx support

### ISSUE THREAD

**Issue by Reaper10** [pasdoc/pasdoc#77]
https://fountain.io/
https://github.com/nyousefi/Fountain

**Comment by michaliskambi** [comment]
I don't think it would be really useful for PasDoc. It's better for us to work on as-full-as-possible [Markdown](https://github.com/pasdoc/pasdoc/wiki/MarkdownOption) support (eventually just having all [GitHub Flavored Markdown](https://github.github.com/gfm/)).

What would Fountain syntax give us? Above what [Markdown](https://github.com/pasdoc/pasdoc/wiki/MarkdownOption) already does? Reading https://fountain.io/faq and https://fountain.io/syntax , I see it's heavily based on Markdown, adding / changing some stuff to be very useful for screenwriting. This sounds like a great idea -- for screenwriters :) We don't really need a special syntax for writing dialogues in PasDoc :)
