### ISSUE TITLE
more syntx highlighters

### ISSUE THREAD

**Issue by Reaper10** [pasdoc/pasdoc#78]
could you add syntx highlighters for Fountain and CriticMarkup?
Fountain 
https://fountain.io/
https://github.com/nyousefi/Fountain

CriticMarkup
http://criticmarkup.com/
https://github.com/CriticMarkup/CriticMarkup-toolkit/

**Comment by Fr0sT-Brutal** [comment]
Could you explain how markdown formats intended for screenwriting (Fountain) and text annotating (CM) will be useful for code description?

**Comment by Reaper10** [comment]
https://www.youtube.com/watch?v=lElhyw3WGxo
https://fountain.io/syntax
is that helpful?

**Comment by Fr0sT-Brutal** [comment]
Absolutely no. Are you going to document communication between classes like dialogues in Shakespeare's style or what?

**Comment by michaliskambi** [comment]
The same answer applies here as I gave for https://github.com/pasdoc/pasdoc/issues/77 :

- These are domain-specific languages that extend Markdown. Fountain is for screenwriters (https://fountain.io/faq https://fountain.io/syntax), CriticMarkup is for annotating text with corrections (http://criticmarkup.com/users-guide.php). They are great ideas... for writing screenplays and for annotating text with corrections. I don't see these enhancements as having much use for PasDoc documentation comments.

    We don't write dialogues, we don't annotate corrections in the documentation. (At least not typically. And if you need to, you can do it well enough IMHO with existing @-tags of PasDoc and existing Markdown support.)

- Our goal is instead to support as-full-as-possible [Markdown](https://github.com/pasdoc/pasdoc/wiki/MarkdownOption), eventually just having all [GitHub Flavored Markdown](https://github.github.com/gfm/) features.

@Reaper10 Please take a look at Markdown, following my links above. It already supports writing text with "intuitive" formatting, similar to what we use here on GitHub actually, e.g. `**this is bold**`. If you have any *specific* feature that is missing from Markdown, but included in Fountain or CriticMarkup, *and* useful for PasDoc (which is: writing documentation), please point it to us.

**Comment by michaliskambi** [comment]
And note that I pretty much agree with everything he said in the video on https://www.youtube.com/watch?v=lElhyw3WGxo . Writing plain text, with really simple markup, is *much* better than using WYSIWYG editors. But we already have a solution for this within PasDoc -- it's Markdown.
