### ISSUE TITLE
[FEATURE REQUEST] Direction of a parameter

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#8]
Hello dudes.

Firstly, thanks for migrating PasDoc to Github hosting, this is one of the most productive platforms for code managment.

So, I'm using Doxygen to generate the documentation of a C library I'm developing, and I found some awesome ideias that maybe useful for PasDoc. For example:

```c
/**
 * Reads a zero-terminated value from string handle @p str.
 * @param[in] str String handle.
 * @param[out] val Value to be read.
 * @param[in,out] len Pointer to specify then store the value length including the terminating null byte (<tt>`\0`</tt>).
 * @retval 0 - Success.
 * @retval -EINVAL - Invalid argument.
 * @retval -ENOBUFS - No buffer space available.
 */
extern int bk_str_read(struct bk_str *str, char *val, size_t *len);
```

It generates something like this:

![image](https://user-images.githubusercontent.com/1456829/36354873-48fbcc96-14b9-11e8-8ec2-3d1772ffbd2c.png)

Notice the `[in]`, `[out]` and `[in,out]` in front of its parameters. It is similar to `var` and `out` of Pascal, or something like a parameter reference pointer. So, in PasDoc-style documenting, it would be:

```pascal
{
  Frees a memory space previous allocated by BrookAlloc().
  @param APtr [in] Pointer of the memory to be freed.
}
procedure BrookFree(APtr: Pointer);
```

and it would generate something like this:

![image](https://user-images.githubusercontent.com/1456829/36354919-222f8228-14ba-11e8-8d9e-d0b0909f227a.png)

What do you thing? :smiley: 

Thank you!

**Comment by michaliskambi** [comment]
1. You can already write `[in]` or `[out]` inside the `@param` description in PasDoc, it will just look different in docs. 

    Explicitly allowing this in PasDoc would simply mean that initial `[xxx]` in parameter description is formatted differently.

2. Whether the parameter is `var` or `our` or `const` (or implicit by-value) is already visible in Pascal declaration. Even in C/C++, the `bk_str_read` could have some parameters `const`, thus clearly showing in the declaration that it's "input" parameter, without the need for `[in]`.

    I know that sometimes it's not that simple, e.g. declaring a `Foo(const Bar: TObject)` in Pascal doesn't clarify whether the contents of `Bar` can be modified. So I agree that sometimes adding an `[in]` (or just saying "the contents of this parameter are not modified") is useful, but that's only sometimes -- in cases of simple types, the Pascal declaration (`var` / `our` / `const` / by-value) already tells you this.

So, I agree this is useful *sometimes*. Although I would not use it for all parameters, but that's up to the developer. I would welcome a patch:)

**Comment by silvioprog** [comment]
@michaliskambi thanks for replying! :smiley: 

The `[in]/[out]` declaration should be optional, so the two declaration below are valid:

1. `@param ASize Memory size to be allocated.` - original
2. `@param [in] ASize Memory size to be allocated.` - extended (maybe 0.16.0)

but the 2. adds the **`[in]`** `ASize` to the documentation.

What do you think?

(I'm busy working in five projects, but I can try to implement it in PasDoc ...)

**Comment by michaliskambi** [comment]
If you can provide a patch (or pull request on GitHub), I would be happy to apply it:)

The implementation should indeed just auto-detect it: If the parameter description starts with `[` then extract the initial `[xxx]` from the description, and place it specifically formatted, like on your screenshots.

Note: I think that we should allow anything inside `[xxx]` (do not limit ourselves to `[in]`, `[out]` etc.). This is for marking "semantics", things beyond what is already visible in the Pascal declaration, so let's allow developer to invent any "tags" he wants. E.g. I may want to sometime use this like

```
@param Obj [nil allowed] This object is used for something.
```

...to explicitly document that Obj may be `nil` (for most of my code, I implicitly require that you pass non-nil references, unless documentation explicitly says that `nil` is handled too).

**Comment by PifPof73** [comment]
Hi,
I made an fork and looked into the code [https://github.com/PifPof73/pasdoc.git](https://github.com/PifPof73/pasdoc.git)

In PasDoc_Utils.pas I would suggest - two constants for the brackets:

``` delphi
  { Tag Start- and Endsign (https://github.com/pasdoc/pasdoc/issues/8) }
  TagStartSign = '[';
  TagEndSign = ']';
```


and than in function ExtractFirstWord:

``` delphi
function ExtractFirstWord(var S: String): String;
var
  Len: Integer;
  StartPos: Integer;
  EndPos: Integer;
  TagStartPos: Integer;
  TagEndPos: Integer;
begin
  StartPos := 1;
  Len := Length(S);

  while (StartPos <= Len) and IsCharInSet(S[StartPos], WhiteSpace) do
    Inc(StartPos);

  if StartPos <= Len then
  begin
    EndPos := StartPos + 1;
    while (EndPos <= Len) and not IsCharInSet(S[EndPos], WhiteSpace) do
      Inc(EndPos);

    { Searching for Tag [in], [out] etc. in Param (see https://github.com/pasdoc/pasdoc/issues/8) }
    TagStartPos := EndPos + 1;
    while (TagStartPos <= Len) and not IsCharInSet(S[TagStartPos], TagStartSign) do
      Inc(TagStartPos);

    if TagStartPos <= Len then
    begin
      TagEndPos := TagStartPos + 1;
      while (TagEndPos <= Len) and not IsCharInset(S[TagEndPos], TagEndSign) do
        Inc(TagEndPos);
    end;

    if TagEndPos <= Len then
      EndPos := TagEndPos;
    { End of Tagsearch issue#8}

    Result := Copy(S, StartPos, EndPos - StartPos);
    S := Trim(Copy(S, EndPos, Len));
  end else
  begin
    { S is only whitespaces }
    Result := '';
    S := '';
  end;
end;
```


I couldn't compile the fork as I am using RIO and there are some compile errors in your type lib.
I try to look after it next week, if I manage to fix it, I will make a test and afterwards a pull request.

Regards,
PifPof73

**Comment by Fr0sT-Brutal** [comment]
@PifPof73 thanks for your initiative!
In fact, building and testing of PasDoc mainly performed on Lazarus which is quite simple to install with distributives. IDK if Delphi packages are tested or even being built.
Parsing of parameters is the easiest part, interesting things start when PasDoc is to output these notes. Hope you'll manage with it ))

**Comment by michaliskambi** [comment]
As for Delphi -- indeed we depend on contributors to test/fix Delphi compatibility occasionally. 
I know me and Jenkins are using FPC (you can get it with Lazarus) to compile, I understand @Fr0sT-Brutal too :)

**Comment by PifPof73** [comment]
> @PifPof73 thanks for your initiative!
> In fact, building and testing of PasDoc mainly performed on Lazarus which is quite simple to install with distributives. IDK if Delphi packages are tested or even being built.
> Parsing of parameters is the easiest part, interesting things start when PasDoc is to output these notes. Hope you'll manage with it ))

@Fr0sT-Brutal 
First things first.
I'm happy that your project exists and I'm using it for the documentation of some projects compiled with Embacadero's Delphi. We are using the latest platform Rio and develop apps for 32bit and 64bit Windows.
There for I want to help you guys and if you need testers for Delphi, I might be your man.

Next week I will try to compile the fork with Delphi and test my first change of your code.

I agree that I took the easy part of this issue - but you have to start somewhere and this request seemed easy enough (and long time open enough) to start from.
If I understood @silvioprog  right, there is no explicit request on formatting the tags specially, as far as I read the request would be fulfilled, if the optional Tag is just took on the parameter site.

If I have a running test equipment I will post the result of my efforts, we can discuss then if we want to style it further more and you could maybe give me a hint or short explanation where to find the output and how the philosophy of styling is (as I'm nooby in your source).
Enjoy the eastern weekend and stay healthy.
Regards, 
PifPof73

**Comment by Fr0sT-Brutal** [comment]
@PifPof73 any help is very appreciated!

In general, the task is

- Elaborate the form of these parameter comments as this would be general extension of @-tag format. I think `[]` is OK because it could be combined with @-tag parameters (`@param[out](some text)`). In the future it could be useful for `@url` tag as well (`@url[example.com] Example link`)
- Add new field to tag object, f.ex., Modifier or something else
- Implement reading contents inside `[]` to that field
- Implement output to all supported text formats

**Comment by PifPof73** [comment]
Hi,
I managed to compile my fork (for testing quick and dirty), and the result without special treating of the direction tags would be like that (as I just added @silvioprog comments befor the routine itself):

![Clipboard01](https://user-images.githubusercontent.com/7371047/79193805-a67b1880-7e2b-11ea-9a73-612e24a4359e.jpg)

Which seems to fullfill the request of @silvioprog.

The output in LaTeX is also close:
![Clipboard02](https://user-images.githubusercontent.com/7371047/79194370-b6dfc300-7e2c-11ea-84e1-24caa678b7e6.jpg)

Please let me know if I should go deeper into it.
Regards,
PifPof73

**Comment by Fr0sT-Brutal** [comment]
@PifPof73 nice job! One little note is a name for the `[ ]` thing. Term "tag" is already occupied by `@smth` so `[ ]` turns to be... wait for it... a tag's tag?

**Comment by michaliskambi** [comment]
Let's call the `[xxx]` a "bracket parameter"? To avoid confuston with "tag", as @Fr0sT-Brutal notes :)

Output looks good -- let's see the code then :) PR is most welcome.

**Comment by PifPof73** [comment]
ok, Tag is a silly name.
As I undetstood its a "direction flag for a parameter".

```Delphi
  { Direction flag for paramters: Start- and Endsign (https://github.com/pasdoc/pasdoc/issues/8) }
  DirectionFlagStartSign = ['['];
  DirectionFlagEndSign = [']'];
```

If that's ok for you I refactor it and make a pull request.
As I am new I have mixed two things in the pull: the changes for making the project compile with RIO and this change - sorry for that.
Regards,
PifPof73

**Comment by michaliskambi** [comment]
> If that's ok for you I refactor it and make a pull request.

Looks cool. "Direction flag" is OK for me.

> As I am new I have mixed two things in the pull: the changes for making the project compile with RIO and this change - sorry for that.

No problem :) It's better to avoid that, but in practice if the change is small, it's not a big deal to "sneak" it alongside another change :)

**Comment by Fr0sT-Brutal** [comment]
> ok, Tag is a silly name.
> As I undetstood its a "direction flag for a parameter".
Maybe just "flag"? We could use this extension later for other tags as well so I vote for more generic naming

**Comment by PifPof73** [comment]
I changed it to flag and made a pull request.

**Comment by michaliskambi** [comment]
The pull request is now applied and tested :) Thank you!

All the details are in https://github.com/pasdoc/pasdoc/pull/84 . I also added an automatic testcase for this to https://github.com/pasdoc/pasdoc/blob/master/tests/testcases/ok_flag_parameter.pas , it can also serve as a demo how to use it :) The testcase results in such output in HTML:
![Screenshot_2020-04-17 ok_flag_parameter](https://user-images.githubusercontent.com/1076978/79605891-0524e880-80f1-11ea-8362-0e32248d1794.png)

As mentioned by others above, there is no special styling for the "flag" part for now. I don't think it's critical, so I let myself close this ticket. If you need different styling, or if you want to work on that -- feel free to create another ticket or pull request :) Thank you all!

**Comment by michaliskambi** [comment]
P.S. Note that in this implementation, the `[xxx]` should be specified *after* the parameter name. Like

```
@param Xxx [in] Some input param.
```

See https://github.com/pasdoc/pasdoc/blob/master/tests/testcases/ok_flag_parameter.pas .

Which is something different than originally proposed. I'm all after changing this, to allow

```
@param [in] Xxx Some input param.
```

I assume @PifPof73  is interested in doing this :) Note that it will require then more involved logic, as @Fr0sT-Brutal was describing. You will need to store this `Flag` contents inside PasDoc_Items data structures, alongside parameter name and description, and you will need to output this specially.

The goal is to have output similar to current (see my post above) or even better (see initial mockup in the 1st post by @silvioprog ). IOW, 

- 1st line displays the parameter name + parameter flag
- 2nd line is indented, and displays the parameter description

Note that writing right now

```
@param [in] Xxx Some input param.
```

is not something I'd advise -- it will work somehow, but just because `[in]` is detected as the first word (this would happen already, before PR #84 anyway), and then the parameter name would be displayed on the 2nd line (so it's not really the correct display).
