### ISSUE TITLE
Compile and build with Delphi Rio 10.3

### ISSUE THREAD

**Issue by PifPof73** [pasdoc/pasdoc#81]
Hi,
I try to compile and build pasdoc under Embacadero Delphi Rio 10.3.
If I do a "compile all" of the project group I get an error saying that the resource file of the gui is missing.

```Delphi
[dcc32 Error] E1026 File not found: 'pasdoc_gui.res
```

Is this file really missing or do I oversee something?
Regards,
PifPof73

**Comment by PifPof73** [comment]
Found that the references of the sub projects were not set right.
I have made a replacement in my fork by removing the Tokyo links and setting new Rio projects.

**Comment by michaliskambi** [comment]
Thanks for investigating. Please submit a PR with this, we'll be happy to apply.
