### ISSUE TITLE
Does PasDoc contain any icon? (PNG or SVG)

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#83]
Hi.

Does PasDoc contain any marketing icon (PNG or SVG)? (e.g. like [this one](https://curl.haxx.se/logo/curl-symbol.svg) for cURL and [this one](https://github.com/neovim/neovim/blob/aa610690bf9e525fcd172def37e14505ac449cf2/runtime/nvim.png) for NeoVIM)

I'm interested to contribute a script [like this](https://github.com/neovim/neovim/blob/aa610690bf9e525fcd172def37e14505ac449cf2/scripts/genappimage.sh) to generate an appimage for PasDoc, making it easier to fix #80, like Linus Torvalds [does for his Subsurface application](https://github.com/Subsurface-divelog/subsurface/blob/84394adb11736de0fa37f7dfb7cf426fcd8f26f5/.github/workflows/scripts/linux-in-container-build.sh#L48).

In general, appimage (and other tools like flatpak/snap etc.) requires sizes 16x16, 32x32, 48x48, 64x64, 128x128 and 256x256, but many applications (GIMP, NeoVIM, KiCAD, Etcher etc.) uses only the 256x256 size, for example, [icons/subsurface-icon.png](https://github.com/Subsurface-divelog/subsurface/blob/61f9c4114e076e77f75db48611283209b33e4202/scripts/build.sh#L550). (BTW, we have been using all sizes in our applications at the company)

cheers

**Comment by michaliskambi** [comment]
We have some icon in https://github.com/pasdoc/pasdoc/tree/master/source/gui/icons . It's hardly a good icon (it's not in SVG, and it is just a text "PasDoc" not a pretty graphical element), improvements are welcome. But it's what we got :)

As for AppImage: I like them, and they seem to gain popularity lately (which is nice, it means that people understand how to run them). If you can provide a script, I'll happily try it.

Questions:

- What will the `PasDoc.AppImage` run? PasDoc is a few binaries right now (`pasdoc`, `pasdoc_gui`, some tools like `file_to_pascal_string`). I guess you just want to run `pasdoc_gui`?

- In case of PasDoc, the benefit of AppImage is only the "sandbox" feature of AppImage, as far as I see. Aside from this, running or distributing `PasDoc.AppImage` isn't any different than just running / distributing  `pasdoc_gui` executable, which is self-contained.

    And in case of `PasDoc.AppImage`, you need to grant the permission to read + write filesystem by the AppImage. So the main remaining purpose of "AppImage sandbox" is to block network access.

    What I'm saying is that the benefit of AppImage over "just get the PasDoc as tar.gz" is small. I haven't heard from anyone the desire to sandbox PasDoc like that, esp. since we're open source project so it's easy to see that we don't do anything nasty.

    E.g. the benefit of Docker ( https://github.com/pasdoc/pasdoc/issues/80 ) is larger, IMHO: a Docker container is an isolated (and tested by devs) environment. It separates your files, it is useful for automation like Jenkins.

**Comment by silvioprog** [comment]
Thanks for sharing the icons! I'll try to create new flat icons based on them (soon).

> What will the PasDoc.AppImage run? PasDoc is a few binaries right now (pasdoc, pasdoc_gui, some tools like file_to_pascal_string). I guess you just want to run pasdoc_gui?

We could start by an appimage for PasDoc GUI and, in a near future, one appimage for each PasDoc tool, automatically generated by travis (or any other CI). :-)

> ... Aside from this, running or distributing PasDoc.AppImage isn't any different than just running / distributing pasdoc_gui executable, which is self-contained.

Maybe, it is not true. The FPC (and maybe Delphi) doesn't link any static library into your executable and doesn't distribute any shared library (GTK2, Cairo etc. required by LCL) that your executable needs to run properly in any Linux distribution.

A `pasdoc_gui` executable generated in release mode is about 8.3 MB, and the user (with admin privileges) must install all required libraries, i.e., if the user don't want GTK2 or don't have root privileges (to install the libraries), he can't run PasDoc GUI. However, an appimage generated for `pasdoc_gui` contains only 6.9 MB (i.e. about 2 MB less) with all dependencies, and any user (even without admin privileges) could run the application properly, without installing any library previously.

The two pictures below shows the appimage content for PasDoc GUI:

![Screenshot_2020-04-17_14-59-54](https://user-images.githubusercontent.com/1456829/79604421-71d5be00-80c4-11ea-8359-e74f2f5f1a81.png)

and all required libraries to run in any Linux distribution:

![Screenshot_2020-04-17_15-00-52](https://user-images.githubusercontent.com/1456829/79604505-95990400-80c4-11ea-8c07-442af1b0f82d.png)

lastly, below an experimental appimage generated to do somes tests:

[PasDoc_GUI-0.15.0-x86_64.tar.gz](https://github.com/pasdoc/pasdoc/files/4494833/PasDoc_GUI-0.15.0-x86_64.tar.gz)

just extract it and run it as ordinary user:

```bash
$  tar -zxvf PasDoc_GUI-0.15.0-x86_64.tar.gz
$ ./PasDoc_GUI-0.15.0-x86_64.AppImage
```

Result:

![image](https://user-images.githubusercontent.com/1456829/79606545-26bdaa00-80c8-11ea-99df-0d0d4aa36d75.png)

**Comment by michaliskambi** [comment]
Hm, it seems you want to package all GTK2 libraries (including dependencies, like X libraries and libpng) inside `PasDoc.AppImage`. Is this a standard practice with AppImage distributions?

I thought that the point of AppImage is to package some additional, not commonly installed, libraries. Not to provide *all* libraries.

GTK and others are part of [Linux Standard Base](https://en.wikipedia.org/wiki/Linux_Standard_Base) and should really be present on all Linux graphical distributions (even KDE-based ones, they include GTK too as far as I know). I thought that AppImage *doesn't* try to include such libraries.

This is important: As a user, with GTK2 and X and LibPNG installed on my system, I would much prefer that the application uses my installed version of these libraries. This is a huge collection of libraries, with fixes (including really important security fixes) happening often, and some distribution-specific changes present too. I would not trust an AppImage that delivers such crucial libraries by itself.

Can you point me to 

- Some AppImage documentation that confirms / denies this? That it is OK / not-OK to package crucial packages (like GTK and X and LibPNG, which are part of LSB)?

- Some example AppImage that follow / unfollow this practice?

Sorry for making this an issue. But this is very important. Distributing ourselves a hardcoded version of GTK / X / LibPNG *is* a big deal, it's a serious risk. These are large libraries that are actively changing.

If this is standard practice of AppImage, then I can accept that. But I need some confirmation about it, preferably from AppImage documentation, if you can find it.

**Comment by Fr0sT-Brutal** [comment]
So, Linux community has invented portable apps? Finally )))) it took a decade for them to get tired fighting with library hell and app content scattering.

**Comment by michaliskambi** [comment]
It's not that new, to be honest :)

- [Snap](https://snapcraft.io/), [Flatpak](https://www.flatpak.org/), [AppImage](https://appimage.org/) are here for some time. 

- And [0install](https://0install.net/) and Autopackage and probably others too. Although they don't offer sandboxing as far as I know, so are generally losing compared to alternatives that do.

Please avoid vague accusations ("it took them a decade", "library hell", "app content scattering"). It's not that easy. The role of distribution packages is still very much needed -- you need a stable system with a set of libraries compatible to each other. E.g. Windows self-installers or macOS "bundle" applications don't redistribute the core components of the respective OS, instead the applications rely on this base to be installed. Linux distributions, with their distribution packages based on tight dependencies, are there to provide this base.

**Comment by michaliskambi** [comment]
@silvioprog Reading about AppImage, and trying more examples, I see that my concern (_"Do we really have to package GTK and X and LibPNG together with PasDoc for AppImage"_) is in practice not considered a problem. That's how AppImage are supposed to be built, they *will* contain all the libraries, even some basic ones.

In return, their "sandbox" feature seems stronger than I thought (good!), and the "recipes" have some similarities to how one defines a Docker image actually. So it's natural that all libraries, even basic ones, are included. Maybe it's even unavoidable.

( I'm curious how does the resulting application e.g. interact with my OpenGL. Since you have to use my OpenGL, provided by my GPU vendor (NVidia etc.) to have the optimal speed of graphics. But that's a question unrelated to PasDoc :) ).

So, I think I answered my own question. Sorry for the noise.

**Comment by silvioprog** [comment]
Just complementing ...

> Hm, it seems you want to package all GTK2 libraries (including dependencies, like X libraries and libpng) inside PasDoc.AppImage.

All required libraries to run the application properly in any Linux distribution, even if the libraries are not installed there.

Some quotes from [AppImage wiki](https://en.wikipedia.org/wiki/AppImage):

_**Objectives**
AppImage aims to be an application deployment system for Linux with the following objectives: simplicity, binary compatibility, distro agnosticism, no installation, no root permission, being portable, and keeping the underlying operating system untouched._

_**Properties**
AppImage does not install the application in the traditional Linux sense. Instead of putting the application's various files in the distro's appropriate places in the file system, the AppImage file is just the application's compressed image. When it runs, the file is mounted with FUSE. This behavior is consistent with AppImage's predecessors, klik and PortableLinuxApps._

> Is this a standard practice with AppImage distributions?

Yes, it is. And IMO it is one of the great things invented by human after discovering fire and inventing wheel. :-)

The main goal of appimage is portability. Many authors of tools written in C/C++/Rust are using it, specially when their applications are published at [conan.io](https://conan.io), Docker hub or just via Github releases page.

AppImage is so popular you probably already used a tool with it before. For example, [Etcher](https://www.balena.io/etcher) is one of the tools distributed as AppImage, and you will found many other tools at [AppImageHub applications](https://appimage.github.io/apps).

**Comment by michaliskambi** [comment]
Thanks for the information. Indeed I used AppImage already with a few applications, I think it's cool from user's perspective.

If it is standard practice to just bundle all libraries, then I'm cool with it :) I'm curious how does the stuff using OpenGL work (which has to use host-specific libraries to have max performance), but this is not related to PasDoc :)

If you can provide a script producing PasDoc.AppImage (that runs pasdoc_gui), I'll happily try it :) I'll also add it to Jenkins so that AppImage is auto-created after every commit on https://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ .

**Comment by silvioprog** [comment]
I'm going to provide small script for it ... :+1:
