### ISSUE TITLE
Implement --lowercase-keywords command-line option

### ISSUE THREAD

**Issue by michaliskambi** [pasdoc/pasdoc#89]
This would control how do the tags `@nil`, `@true`, `@false` look like in the output. Right now, they start with an upper letter, like `Nil`. Use this option to make them all lowercase, like `nil`.

**Comment by Fr0sT-Brutal** [comment]
Nice but usual (used in RTL) style of Boolean values is first letter up and style of nil is first letter low :)

**Comment by silvioprog** [comment]
@Fr0sT-Brutal, indeed. GNU Pascal, JEDI project and (Borland/)Embarcadero Delphi use `Boolean`/`nil` in their conventions(*) too, i.e all reserved words from ISO Pascal (e.g `string`, `nil`, `far`, `cdecl` etc.) are lower-case, ordinary types are CapitalizedWords (or PascalCase) and reserved words in early Delphi use CapitalizedWords too (e.g `WideString`, `UnicodeString` etc.).

GNU Pascal -> https://www.gnu-pascal.de/h-gpcs-en.html
JEDI -> https://wiki.delphi-jedi.org/wiki/Project_JEDI_Delphi_Language_Style_Guide
For Delphi found these references -> https://www.win.tue.nl/~wstomv/edu/delphi/DelphiLanguageGuide.pdf, http://box.cs.istu.ru/public/docs/other/_New/Books/Lang/Delphi/Delphi%20Developer's%20Guide/Ebooks/d5dg/chapter6.pdf, http://www.sourceformat.com/coding-standard-delphi-econos.htm and http://web.archive.org/web/20170124021121/http://delphi.about.com/od/standards/l/bldnc.htm

**Comment by michaliskambi** [comment]
It is actually wildly inconsistent :)

```
$ svn info
...
URL: https://svn.freepascal.org/svn/fpc/branches/fixes_3_2
Wersja: 45044
...

$ grep -R True packages/ | wc -l
12713
$ grep -R true packages/ | wc -l
8757

# So True wins in packages/, by a small margin

$ grep -R True rtl/ | wc -l
422
$ grep -R true rtl/ | wc -l
930

# So true wins in rtl/, by a large margin (2x)

$ grep -R true compiler/ | wc -l
4504
$ grep -R True compiler/ | wc -l
512

# So true wins in compiler/, by a very large margin

cd ../lazarus/

$ grep -R --exclude=*.lfm  --exclude=*.xml  --exclude=*.po True  * | wc -l
20383
$ grep -R --exclude=*.lfm  --exclude=*.xml  --exclude=*.po true  * | wc -l
11074

# So True wins in Lazarus by a large margin (2x)
```

**Comment by silvioprog** [comment]
Well, FPC and Lazarus are not a good reference for coding convention / coding style, since anyone writes as their can. :-)

**Comment by Fr0sT-Brutal** [comment]
Yeah, FPC/Lazarus have no styling guides and are very easy with casing, spacing and such. I'd take Delphi RTL as a strict coding style standard
