### ISSUE TITLE
Go to index page when clicking in the project title

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#93]
It would be nice to navigate to the index page when clicking in the project title. For example, if the title "Brook Tardigrade" is clicked, it navigates to its [index page](https://risoflora.github.io/brookframework-docs/index.html).

**Comment by Bi0T1N** [comment]
I think that changing
```pascal
    if Title <> '' then
      Result := Result + '<h2>' + ConvertString(Title) + '</h2>';
```
to
```pascal
    if Title <> '' then
    begin
      if Introduction <> nil then
        Result := Result + '<h2><a href="' + EscapeURL(Introduction.OutputFileName) + '" class="navigation">' + ConvertString(Title) + '</a></h2>'
      else
        Result := Result + '<h2><a href="' + EscapeURL('AllUnits.html') + '" class="navigation">' + ConvertString(Title) + '</a></h2>'
    end;
```
in [PasDoc_GenHtml.pas#L2519](https://github.com/pasdoc/pasdoc/blob/master/source/component/PasDoc_GenHtml.pas#L2519) should achieve it. Haven't tested yet.

**Comment by michaliskambi** [comment]
Thanks to @Bi0T1N for implementing! I quickly tested it -- great.

**Comment by silvioprog** [comment]
I'm going to use it in my new documentations! Thank you @Bi0T1N ! :-) 👍
