### ISSUE TITLE
Update Tipue Search and jQuery files

### ISSUE THREAD

**Issue by Bi0T1N** [pasdoc/pasdoc#97]
- Tipue Search website says current version is 7.1 while pasdoc uses 6.1 (changelog entry for next version is already 2 years old)
- the jQuery file headers are saying _jQuery JavaScript Library v2.0.0_  while the current version is 3.5.1

**Comment by michaliskambi** [comment]
:+1: Indeed we should upgrade (and test that new version works OK :) ). PRs are welcome :)

**Comment by Bi0T1N** [comment]
Fixed with #100
